// Static content: roadmap weeks, problems, topic notes, company tiers.
// Problem level l: 1 = core (everyone), 2 = mid (mid-size/startup), 3 = stretch (big tech).

const WEEKS = [
  { n: 1, title: "Arrays & Hashing", cats: ["arrays"] },
  { n: 2, title: "Two Pointers & Sliding Window", cats: ["twoptr", "window"] },
  { n: 3, title: "Stack & Binary Search", cats: ["stack", "bsearch"] },
  { n: 4, title: "Linked Lists", cats: ["linked"] },
  { n: 5, title: "Trees", cats: ["trees"] },
  { n: 6, title: "Heaps & Tries", cats: ["heap", "trie"] },
  { n: 7, title: "Backtracking", cats: ["backtrack"] },
  { n: 8, title: "Graphs (BFS/DFS/Topo/Union-Find)", cats: ["graphs"] },
  { n: 9, title: "Intervals, Greedy, Matrix & Bits", cats: ["greedy", "math"] },
  { n: 10, title: "Dynamic Programming I (1-D)", cats: ["dp1"] },
  { n: 11, title: "Dynamic Programming II (2-D) + Catch-up", cats: ["dp2"] },
  { n: 12, title: "Mock Interviews & Review", cats: [] },
];

const CATS = {
  arrays: "Arrays & Hashing", twoptr: "Two Pointers", window: "Sliding Window", stack: "Stack",
  bsearch: "Binary Search", linked: "Linked List", trees: "Trees", heap: "Heap", trie: "Trie",
  backtrack: "Backtracking", graphs: "Graphs", greedy: "Intervals & Greedy", math: "Math, Matrix & Bits",
  dp1: "1-D DP", dp2: "2-D DP",
};

// [title, leetcode-slug, difficulty E/M/H, category, level]
const P = (t, s, d, c, l) => ({ t, s, d, c, l });
const PROBLEMS = [
  // Arrays & Hashing
  P("Contains Duplicate", "contains-duplicate", "E", "arrays", 1),
  P("Valid Anagram", "valid-anagram", "E", "arrays", 1),
  P("Two Sum", "two-sum", "E", "arrays", 1),
  P("Majority Element", "majority-element", "E", "arrays", 1),
  P("Move Zeroes", "move-zeroes", "E", "arrays", 1),
  P("Group Anagrams", "group-anagrams", "M", "arrays", 1),
  P("Top K Frequent Elements", "top-k-frequent-elements", "M", "arrays", 1),
  P("Product of Array Except Self", "product-of-array-except-self", "M", "arrays", 1),
  P("Valid Sudoku", "valid-sudoku", "M", "arrays", 2),
  P("Longest Consecutive Sequence", "longest-consecutive-sequence", "M", "arrays", 2),
  P("Subarray Sum Equals K", "subarray-sum-equals-k", "M", "arrays", 2),
  P("Rotate Array", "rotate-array", "M", "arrays", 2),
  // Two pointers
  P("Valid Palindrome", "valid-palindrome", "E", "twoptr", 1),
  P("Remove Duplicates from Sorted Array", "remove-duplicates-from-sorted-array", "E", "twoptr", 1),
  P("Two Sum II - Input Array Is Sorted", "two-sum-ii-input-array-is-sorted", "M", "twoptr", 1),
  P("3Sum", "3sum", "M", "twoptr", 1),
  P("Container With Most Water", "container-with-most-water", "M", "twoptr", 2),
  P("Sort Colors", "sort-colors", "M", "twoptr", 2),
  P("Trapping Rain Water", "trapping-rain-water", "H", "twoptr", 3),
  // Sliding window
  P("Best Time to Buy and Sell Stock", "best-time-to-buy-and-sell-stock", "E", "window", 1),
  P("Maximum Average Subarray I", "maximum-average-subarray-i", "E", "window", 1),
  P("Longest Substring Without Repeating Characters", "longest-substring-without-repeating-characters", "M", "window", 1),
  P("Longest Repeating Character Replacement", "longest-repeating-character-replacement", "M", "window", 2),
  P("Permutation in String", "permutation-in-string", "M", "window", 2),
  P("Minimum Window Substring", "minimum-window-substring", "H", "window", 3),
  P("Sliding Window Maximum", "sliding-window-maximum", "H", "window", 3),
  // Stack
  P("Valid Parentheses", "valid-parentheses", "E", "stack", 1),
  P("Min Stack", "min-stack", "M", "stack", 1),
  P("Daily Temperatures", "daily-temperatures", "M", "stack", 1),
  P("Evaluate Reverse Polish Notation", "evaluate-reverse-polish-notation", "M", "stack", 2),
  P("Car Fleet", "car-fleet", "M", "stack", 3),
  P("Largest Rectangle in Histogram", "largest-rectangle-in-histogram", "H", "stack", 3),
  // Binary search
  P("Binary Search", "binary-search", "E", "bsearch", 1),
  P("Search a 2D Matrix", "search-a-2d-matrix", "M", "bsearch", 1),
  P("Koko Eating Bananas", "koko-eating-bananas", "M", "bsearch", 2),
  P("Find Minimum in Rotated Sorted Array", "find-minimum-in-rotated-sorted-array", "M", "bsearch", 2),
  P("Search in Rotated Sorted Array", "search-in-rotated-sorted-array", "M", "bsearch", 2),
  P("Time Based Key-Value Store", "time-based-key-value-store", "M", "bsearch", 3),
  P("Median of Two Sorted Arrays", "median-of-two-sorted-arrays", "H", "bsearch", 3),
  // Linked list
  P("Reverse Linked List", "reverse-linked-list", "E", "linked", 1),
  P("Merge Two Sorted Lists", "merge-two-sorted-lists", "E", "linked", 1),
  P("Linked List Cycle", "linked-list-cycle", "E", "linked", 1),
  P("Middle of the Linked List", "middle-of-the-linked-list", "E", "linked", 1),
  P("Reorder List", "reorder-list", "M", "linked", 2),
  P("Remove Nth Node From End of List", "remove-nth-node-from-end-of-list", "M", "linked", 2),
  P("Add Two Numbers", "add-two-numbers", "M", "linked", 2),
  P("LRU Cache", "lru-cache", "M", "linked", 2),
  P("Copy List with Random Pointer", "copy-list-with-random-pointer", "M", "linked", 3),
  P("Merge k Sorted Lists", "merge-k-sorted-lists", "H", "linked", 3),
  // Trees
  P("Invert Binary Tree", "invert-binary-tree", "E", "trees", 1),
  P("Maximum Depth of Binary Tree", "maximum-depth-of-binary-tree", "E", "trees", 1),
  P("Same Tree", "same-tree", "E", "trees", 1),
  P("Diameter of Binary Tree", "diameter-of-binary-tree", "E", "trees", 2),
  P("Balanced Binary Tree", "balanced-binary-tree", "E", "trees", 2),
  P("Subtree of Another Tree", "subtree-of-another-tree", "E", "trees", 2),
  P("Lowest Common Ancestor of a Binary Search Tree", "lowest-common-ancestor-of-a-binary-search-tree", "M", "trees", 1),
  P("Binary Tree Level Order Traversal", "binary-tree-level-order-traversal", "M", "trees", 1),
  P("Validate Binary Search Tree", "validate-binary-search-tree", "M", "trees", 1),
  P("Binary Tree Right Side View", "binary-tree-right-side-view", "M", "trees", 2),
  P("Kth Smallest Element in a BST", "kth-smallest-element-in-a-bst", "M", "trees", 2),
  P("Count Good Nodes in Binary Tree", "count-good-nodes-in-binary-tree", "M", "trees", 2),
  P("Construct Binary Tree from Preorder and Inorder Traversal", "construct-binary-tree-from-preorder-and-inorder-traversal", "M", "trees", 3),
  P("Binary Tree Maximum Path Sum", "binary-tree-maximum-path-sum", "H", "trees", 3),
  P("Serialize and Deserialize Binary Tree", "serialize-and-deserialize-binary-tree", "H", "trees", 3),
  // Heap
  P("Last Stone Weight", "last-stone-weight", "E", "heap", 1),
  P("Kth Largest Element in a Stream", "kth-largest-element-in-a-stream", "E", "heap", 2),
  P("Kth Largest Element in an Array", "kth-largest-element-in-an-array", "M", "heap", 1),
  P("K Closest Points to Origin", "k-closest-points-to-origin", "M", "heap", 2),
  P("Task Scheduler", "task-scheduler", "M", "heap", 3),
  P("Find Median from Data Stream", "find-median-from-data-stream", "H", "heap", 3),
  // Trie
  P("Implement Trie (Prefix Tree)", "implement-trie-prefix-tree", "M", "trie", 2),
  P("Design Add and Search Words Data Structure", "design-add-and-search-words-data-structure", "M", "trie", 3),
  P("Word Search II", "word-search-ii", "H", "trie", 3),
  // Backtracking
  P("Subsets", "subsets", "M", "backtrack", 1),
  P("Combination Sum", "combination-sum", "M", "backtrack", 1),
  P("Permutations", "permutations", "M", "backtrack", 1),
  P("Generate Parentheses", "generate-parentheses", "M", "backtrack", 2),
  P("Word Search", "word-search", "M", "backtrack", 2),
  P("Letter Combinations of a Phone Number", "letter-combinations-of-a-phone-number", "M", "backtrack", 2),
  P("Palindrome Partitioning", "palindrome-partitioning", "M", "backtrack", 2),
  P("N-Queens", "n-queens", "H", "backtrack", 3),
  // Graphs
  P("Find if Path Exists in Graph", "find-if-path-exists-in-graph", "E", "graphs", 1),
  P("Number of Islands", "number-of-islands", "M", "graphs", 1),
  P("Max Area of Island", "max-area-of-island", "M", "graphs", 1),
  P("Course Schedule", "course-schedule", "M", "graphs", 1),
  P("Clone Graph", "clone-graph", "M", "graphs", 2),
  P("Rotting Oranges", "rotting-oranges", "M", "graphs", 2),
  P("Course Schedule II", "course-schedule-ii", "M", "graphs", 2),
  P("Pacific Atlantic Water Flow", "pacific-atlantic-water-flow", "M", "graphs", 3),
  P("Surrounded Regions", "surrounded-regions", "M", "graphs", 3),
  P("Redundant Connection", "redundant-connection", "M", "graphs", 3),
  P("Network Delay Time", "network-delay-time", "M", "graphs", 3),
  P("Cheapest Flights Within K Stops", "cheapest-flights-within-k-stops", "M", "graphs", 3),
  P("Word Ladder", "word-ladder", "H", "graphs", 3),
  // Intervals & greedy
  P("Maximum Subarray", "maximum-subarray", "M", "greedy", 1),
  P("Jump Game", "jump-game", "M", "greedy", 1),
  P("Merge Intervals", "merge-intervals", "M", "greedy", 1),
  P("Insert Interval", "insert-interval", "M", "greedy", 2),
  P("Non-overlapping Intervals", "non-overlapping-intervals", "M", "greedy", 2),
  P("Jump Game II", "jump-game-ii", "M", "greedy", 3),
  P("Gas Station", "gas-station", "M", "greedy", 3),
  P("Partition Labels", "partition-labels", "M", "greedy", 3),
  // Math, matrix, bits
  P("Single Number", "single-number", "E", "math", 1),
  P("Plus One", "plus-one", "E", "math", 1),
  P("Number of 1 Bits", "number-of-1-bits", "E", "math", 2),
  P("Counting Bits", "counting-bits", "E", "math", 2),
  P("Missing Number", "missing-number", "E", "math", 2),
  P("Happy Number", "happy-number", "E", "math", 2),
  P("Rotate Image", "rotate-image", "M", "math", 2),
  P("Spiral Matrix", "spiral-matrix", "M", "math", 2),
  P("Set Matrix Zeroes", "set-matrix-zeroes", "M", "math", 2),
  P("Pow(x, n)", "powx-n", "M", "math", 3),
  P("Reverse Integer", "reverse-integer", "M", "math", 3),
  // 1-D DP
  P("Climbing Stairs", "climbing-stairs", "E", "dp1", 1),
  P("Min Cost Climbing Stairs", "min-cost-climbing-stairs", "E", "dp1", 1),
  P("House Robber", "house-robber", "M", "dp1", 1),
  P("Coin Change", "coin-change", "M", "dp1", 1),
  P("House Robber II", "house-robber-ii", "M", "dp1", 2),
  P("Longest Palindromic Substring", "longest-palindromic-substring", "M", "dp1", 2),
  P("Decode Ways", "decode-ways", "M", "dp1", 2),
  P("Word Break", "word-break", "M", "dp1", 2),
  P("Longest Increasing Subsequence", "longest-increasing-subsequence", "M", "dp1", 2),
  P("Palindromic Substrings", "palindromic-substrings", "M", "dp1", 3),
  P("Maximum Product Subarray", "maximum-product-subarray", "M", "dp1", 3),
  P("Partition Equal Subset Sum", "partition-equal-subset-sum", "M", "dp1", 3),
  // 2-D DP
  P("Unique Paths", "unique-paths", "M", "dp2", 1),
  P("Longest Common Subsequence", "longest-common-subsequence", "M", "dp2", 2),
  P("Coin Change II", "coin-change-ii", "M", "dp2", 3),
  P("Target Sum", "target-sum", "M", "dp2", 3),
  P("Best Time to Buy and Sell Stock with Cooldown", "best-time-to-buy-and-sell-stock-with-cooldown", "M", "dp2", 3),
  P("Edit Distance", "edit-distance", "M", "dp2", 3),
];

// Short study notes per category: recognise it, how to do it, complexity, Python template.
const NOTES = {
  arrays: {
    spot: "Need fast lookup, counting, grouping, or 'have I seen this?' Think hash map / set first.",
    how: "Trade space for time: store seen values, counts, or prefix sums in a dict. Sort only if order helps. Prefix/suffix arrays solve 'everything except self' style problems.",
    big: "Usually O(n) time, O(n) space (vs O(n^2) brute force).",
    code: "from collections import Counter, defaultdict\n\ndef two_sum(nums, target):\n    seen = {}                      # value -> index\n    for i, x in enumerate(nums):\n        if target - x in seen:\n            return [seen[target - x], i]\n        seen[x] = i\n\n# prefix sums: count subarrays summing to k\ndef subarray_sum(nums, k):\n    count, pre, freq = 0, 0, {0: 1}\n    for x in nums:\n        pre += x\n        count += freq.get(pre - k, 0)\n        freq[pre] = freq.get(pre, 0) + 1\n    return count",
  },
  twoptr: {
    spot: "Sorted array/string, pairs or triples that meet a condition, palindromes, in-place rewriting.",
    how: "Two indices moving toward each other (sorted input) or a slow/fast pair (in-place filtering). Move the pointer that can improve the answer.",
    big: "O(n) time, O(1) space (O(n log n) if you must sort first).",
    code: "def two_sum_sorted(a, target):\n    l, r = 0, len(a) - 1\n    while l < r:\n        s = a[l] + a[r]\n        if s == target: return [l, r]\n        if s < target: l += 1\n        else: r -= 1",
  },
  window: {
    spot: "Contiguous subarray/substring that is longest, shortest, or best under a constraint.",
    how: "Expand right, shrink left while the window is invalid, record the best. Track state with a dict/counter or running sum. Fixed-size windows just slide.",
    big: "O(n) time; each element enters and leaves once.",
    code: "def longest_unique(s):\n    last, l, best = {}, 0, 0\n    for r, ch in enumerate(s):\n        if ch in last and last[ch] >= l:\n            l = last[ch] + 1\n        last[ch] = r\n        best = max(best, r - l + 1)\n    return best",
  },
  stack: {
    spot: "Matching brackets, 'next greater/smaller element', undo/nesting, expression evaluation.",
    how: "Push while waiting for an answer; pop when the current element resolves it. Monotonic stack: keep the stack sorted so pops are the answers.",
    big: "O(n) amortized.",
    code: "def daily_temps(t):\n    res, st = [0] * len(t), []     # st holds indices, temps decreasing\n    for i, x in enumerate(t):\n        while st and t[st[-1]] < x:\n            j = st.pop()\n            res[j] = i - j\n        st.append(i)\n    return res",
  },
  bsearch: {
    spot: "Sorted or rotated data, or any 'minimum value such that condition holds' (monotonic yes/no).",
    how: "Keep an invariant on [l, r]. For 'search on answer', binary search the value range and test feasibility with a helper function.",
    big: "O(log n) time (times the cost of the feasibility check).",
    code: "def lower_bound(a, target):        # first index with a[i] >= target\n    l, r = 0, len(a)\n    while l < r:\n        m = (l + r) // 2\n        if a[m] < target: l = m + 1\n        else: r = m\n    return l",
  },
  linked: {
    spot: "Pointer rewiring, cycles, middle, merging, in-place reversal.",
    how: "Use a dummy head to avoid edge cases. Fast/slow pointers find middle and cycles. Reverse with prev/curr/next. LRU cache = hash map + doubly linked list.",
    big: "O(n) time, O(1) space for most.",
    code: "def reverse(head):\n    prev = None\n    while head:\n        head.next, prev, head = prev, head, head.next\n    return prev\n\ndef has_cycle(head):\n    slow = fast = head\n    while fast and fast.next:\n        slow, fast = slow.next, fast.next.next\n        if slow is fast: return True\n    return False",
  },
  trees: {
    spot: "Hierarchies, BST properties, depth/height, paths, level-by-level questions.",
    how: "DFS (recursion) for depth, paths, validation: decide what each call returns and what it passes down. BFS with a deque for levels. BST: inorder is sorted.",
    big: "O(n) time; O(h) stack space (h = height).",
    code: "from collections import deque\n\ndef max_depth(root):\n    return 0 if not root else 1 + max(max_depth(root.left), max_depth(root.right))\n\ndef level_order(root):\n    res, q = [], deque([root] if root else [])\n    while q:\n        res.append([n.val for n in q])\n        for _ in range(len(q)):\n            n = q.popleft()\n            q.extend(c for c in (n.left, n.right) if c)\n    return res",
  },
  heap: {
    spot: "Top-k, k-th largest/smallest, repeatedly taking the min/max, merging sorted streams, running median.",
    how: "heapq is a min-heap; negate values for a max-heap. Keep a heap of size k for top-k. Two heaps (max + min) give a running median.",
    big: "O(n log k) time, O(k) space.",
    code: "import heapq\n\ndef kth_largest(nums, k):\n    h = []\n    for x in nums:\n        heapq.heappush(h, x)\n        if len(h) > k: heapq.heappop(h)\n    return h[0]",
  },
  trie: {
    spot: "Prefix lookups, autocomplete, dictionary word search on a grid.",
    how: "Each node holds children keyed by character plus an end-of-word flag. Prune the search when no child matches.",
    big: "O(L) per insert/search (L = word length).",
    code: "class Trie:\n    def __init__(self):\n        self.root = {}\n    def insert(self, w):\n        n = self.root\n        for c in w: n = n.setdefault(c, {})\n        n['$'] = True\n    def starts_with(self, p):\n        n = self.root\n        for c in p:\n            if c not in n: return False\n            n = n[c]\n        return True",
  },
  backtrack: {
    spot: "'Generate all' subsets, permutations, combinations, placements. Small input (n <= ~20).",
    how: "Choose, explore, un-choose. Define the state (path, start index, remaining), the base case, and prune invalid branches early. Skip duplicates by sorting and skipping equal neighbours.",
    big: "Exponential: O(2^n) subsets, O(n!) permutations.",
    code: "def subsets(nums):\n    res, path = [], []\n    def dfs(i):\n        if i == len(nums):\n            res.append(path[:]); return\n        path.append(nums[i]); dfs(i + 1)   # take\n        path.pop();          dfs(i + 1)   # skip\n    dfs(0)\n    return res",
  },
  graphs: {
    spot: "Grids, networks, dependencies, 'connected', 'shortest path', 'order of tasks'.",
    how: "Build an adjacency list. BFS = shortest path in unweighted graphs; DFS = connectivity/components; topological sort (Kahn's) = dependency order & cycle detection; Union-Find = dynamic connectivity; Dijkstra (heap) = weighted shortest path. Mark visited to avoid loops.",
    big: "O(V + E) for BFS/DFS/topo; O((V + E) log V) for Dijkstra.",
    code: "from collections import deque\n\ndef num_islands(g):\n    R, C, seen = len(g), len(g[0]), set()\n    def bfs(r, c):\n        q = deque([(r, c)]); seen.add((r, c))\n        while q:\n            x, y = q.popleft()\n            for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):\n                nx, ny = x + dx, y + dy\n                if 0 <= nx < R and 0 <= ny < C and g[nx][ny] == '1' and (nx, ny) not in seen:\n                    seen.add((nx, ny)); q.append((nx, ny))\n    n = 0\n    for r in range(R):\n        for c in range(C):\n            if g[r][c] == '1' and (r, c) not in seen:\n                bfs(r, c); n += 1\n    return n",
  },
  greedy: {
    spot: "Intervals, scheduling, 'minimum number of ...', local best choice seems safe.",
    how: "Sort (usually by start or end), then sweep. Merge when overlapping. For greedy, convince yourself with an exchange argument or counter-example search.",
    big: "O(n log n) from the sort.",
    code: "def merge(intervals):\n    intervals.sort()\n    out = [intervals[0]]\n    for s, e in intervals[1:]:\n        if s <= out[-1][1]: out[-1][1] = max(out[-1][1], e)\n        else: out.append([s, e])\n    return out",
  },
  math: {
    spot: "Matrix manipulation, bit tricks, number properties.",
    how: "XOR cancels pairs; n & (n-1) clears the lowest set bit. For matrices, think layer by layer or transpose + reverse. Watch overflow rules the problem states.",
    big: "Typically O(n) or O(rows*cols), O(1) extra space.",
    code: "def single_number(nums):\n    x = 0\n    for n in nums: x ^= n\n    return x\n\ndef rotate(m):                       # 90 degrees clockwise, in place\n    m.reverse()\n    for i in range(len(m)):\n        for j in range(i):\n            m[i][j], m[j][i] = m[j][i], m[i][j]",
  },
  dp1: {
    spot: "'Number of ways', 'min/max cost', 'can we reach', overlapping subproblems on a sequence.",
    how: "1) Define dp[i] in words. 2) Write the recurrence. 3) Base cases. 4) Order of fill (or memoize with @cache). 5) Compress space if only the last 1-2 states are needed.",
    big: "Usually O(n) or O(n * amount) time.",
    code: "from functools import cache\n\ndef coin_change(coins, amount):\n    INF = float('inf')\n    dp = [0] + [INF] * amount\n    for a in range(1, amount + 1):\n        for c in coins:\n            if c <= a: dp[a] = min(dp[a], dp[a - c] + 1)\n    return dp[amount] if dp[amount] != INF else -1",
  },
  dp2: {
    spot: "Two strings/sequences, grids, knapsack-style choices (index + remaining capacity).",
    how: "dp[i][j] over two prefixes (LCS, edit distance) or grid cells. Match -> diagonal + 1 or carry; mismatch -> best of neighbours. Roll rows to save memory.",
    big: "O(m * n) time, O(n) space after rolling.",
    code: "def lcs(a, b):\n    dp = [[0] * (len(b) + 1) for _ in range(len(a) + 1)]\n    for i in range(1, len(a) + 1):\n        for j in range(1, len(b) + 1):\n            if a[i-1] == b[j-1]: dp[i][j] = dp[i-1][j-1] + 1\n            else: dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n    return dp[-1][-1]",
  },
};

// Region company tiers. Emphasis is a general guide, not insider info: always check
// current interview reports (Glassdoor, Levels.fyi, LeetCode Discuss, Blind) and job postings.
const TIERS = [
  {
    id: 1, name: "Big tech & top-paying product companies", bar: "Highest bar", levels: 3,
    emphasis: "Mediums plus some Hards: graphs, DP, trees, heaps, sliding window, plus system design for mid-level. Expect 2-4 coding rounds, often on a shared doc or CoderPad.",
    focus: ["graphs", "dp1", "dp2", "trees", "heap", "window", "backtrack"],
    names: ["Google (Kitchener-Waterloo / Toronto)", "Amazon (Toronto)", "Microsoft", "Shopify", "Cohere", "Intuit", "Uber (Toronto)"],
  },
  {
    id: 2, name: "Mid-size tech & startups", bar: "Medium bar", levels: 2,
    emphasis: "Easy-to-medium DSA (arrays, hashing, trees, BFS/DFS, basic DP), often mixed with practical coding, take-home projects, and past-experience / system design discussion.",
    focus: ["arrays", "twoptr", "window", "trees", "graphs", "stack", "linked", "bsearch"],
    names: ["Faire", "Clio", "Wealthsimple", "D2L", "OpenText", "Descartes", "Dayforce", "Thomson Reuters", "Miovision", "Magnet Forensics", "Communitech-area startups"],
  },
  {
    id: 3, name: "Banks, insurers & other local employers", bar: "Lower DSA bar", levels: 1,
    emphasis: "Easy/medium fundamentals: arrays, strings, hashing, linked lists, trees, sorting/searching. Interviews are often behavioural + a CoderPad or HackerRank screen + SQL/OOP/design questions. Communication and clean code matter a lot.",
    focus: ["arrays", "twoptr", "linked", "trees", "stack", "bsearch"],
    names: ["RBC", "TD", "Scotiabank", "BMO", "CIBC", "Manulife", "Sun Life", "Canada Life", "Intact", "Equitable Bank", "Ontario Public Service"],
  },
];

// Mock interview / review prompts used in week 12 and the Mock tab.
const MOCK_TIPS = [
  "Restate the problem and confirm inputs, outputs, and constraints out loud.",
  "Work a small example by hand, then name the brute-force approach and its cost.",
  "Optimise: which repeated work can a hash map, sorting, or two pointers remove?",
  "State the plan before you code. Then code cleanly with meaningful names.",
  "Test with a normal case, an edge case (empty, one element), and a tricky case.",
  "Finish with time and space complexity.",
];
