// Every video in each IBM Technology playlist shown on the IBM Videos tab: [videoId, title, length].
// Generated from YouTube on 2026-10-06; unavailable or private videos are left out.
const IBM_PLAYLIST_VIDEOS = {
  "PLOspHqNVtKADfxkuDuHduUkDExBpEt3DF": [
    ["kyJ1vd7yEPc", "AI Is Exposing Your Data: An AI Security Problem You Can't See", "11:29"],
    ["mUw27wG7uFA", "AI Simplified: 6 Concepts You Need to Know About Modern AI", "8:49"],
    ["X4FVEEegCbk", "Skills vs MCP vs RAG vs Memory: What AI Agents Need to Know", "9:11"],
    ["ZELPNFXJ4_o", "AI Model vs Agentic Harness: What Actually Drives AI", "8:30"],
    ["i1ZmNUbRGD4", "AI Agents vs Business Rules: Which Should Make Decisions?", "10:25"],
    ["J0zbWsutyA8", "What Is RAD? Why It Matters in the Age of AI Coding", "10:53"],
    ["Qx0fCqpkBus", "What Is Context Engineering? Why It Matters for AI Agents", "9:57"],
    ["uhWFLmr7xao", "What Is AI Model Collapse? Why AI Could Forget Reality", "13:10"],
    ["uU1EP9_4qBU", "What Are Large Database Models? AI for SQL Data", "13:55"],
    ["FgaBdwSvOGM", "Agentic Engineering vs Software Engineering: Beyond Vibe Coding", "10:46"],
    ["0ujh7hfutq0", "Llama.cpp vs vLLM: Which Local LLM Engine Actually Scales?", "10:36"],
    ["fWZylhIHF9w", "What Is an AI IDE? How AI Is Changing Developer & Coding Tools", "8:47"],
    ["SVAwzodyFUo", "How to Manage Your AI Before It Makes the Wrong Decision", "8:50"],
    ["ZVPlLaehjLk", "Agentic AI Frameworks Explained: Workflows, Multi-Agent, & Production", "11:54"],
    ["goU9VIXA8II", "MCP vs Skills: Which Is Right for Your AI Agent and LLMs?", "8:03"],
    ["0-YCleDw-Po", "What Is AI Code Review? Fixing Slow PRs & Broken Workflows with AI", "10:53"],
    ["k5jYwyhDMxA", "5 AI Agent Terms You Need to Know", "11:07"],
    ["MTmhgIVhpag", "What Is AI Pair Programming? AI Coding Tools for Developers", "7:16"],
    ["PjrXaC5UsIw", "What Is Agentic Coding? How AI Agents Modernize Code", "10:21"],
    ["DAlC8mL5ZlI", "Why AI Models Pause to Think: Test Time Compute Explained", "10:32"],
    ["kYkZI3oj2W4", "Multi AI Agent Systems: When One AI Brain Isn’t Enough", "10:55"],
    ["BacJ6sEhqMo", "The Four Types of Memory Every AI Agent Needs", "10:41"],
    ["eGoszzMkGfU", "Graph Neural Networks Explained: A Clear Guide to GNN Basics & Models", "16:47"],
    ["1m55T8xST9s", "Five AI Risks That Can Get You Fired—And How to Avoid Them", "10:58"],
    ["B_RrXwDupIg", "CAG vs Long Context: How AI Models Use and Remember Information", "10:59"],
    ["BedAaB1RKgE", "MCP vs ADK: How Modern AI Agents Connect and Work Together", "14:11"],
    ["D37Ijn2o5U0", "Why Agentic AI Fails: Infinite Loops, Planning Errors, and More", "12:45"],
    ["phOhGqpXss4", "Predictive vs Generative AI: How They Work and When to Use Each", "11:59"],
    ["7HSSR1n8dgc", "ADK vs RAG: How to Choose the Right AI Stack", "6:31"],
    ["Lg-meK5IU8Q", "What AI Agent Skills Are and How They Work", "12:25"],
    ["mtiOK2QG9Q0", "The 7 Skills You Need to Build AI Agents", "14:37"],
    ["GOsnf5lOIrI", "What is Physical AI? How Robots Learn & Adapt in Real Life", "8:52"],
    ["DgXV8QSlI4U", "What is AI Technical Debt? Key Risks for Machine Learning Projects", "13:33"],
    ["J51oZYcNvP8", "What is Multimodal AI? How LLMs Process Text, Images, and More", "9:15"],
    ["9iS-YYLIXiw", "What is Human In The Loop with AI? How HITL Shapes AI Systems", "10:44"],
    ["BMDFPOyezH4", "A2A vs MCP: AI Agent Communication Explained", "11:46"],
    ["ZfWDVO3rzeA", "What Is NeuroSymbolic AI? Bridging Reasoning & Neural Networks", "5:47"],
    ["anLahYrEFiQ", "What is Multimodal RAG? Unlocking LLMs with Vector Databases", "11:13"],
    ["u57EnkQaUTY", "What is Prompt Caching? Optimize LLM Latency with AI Transformers", "9:06"],
    ["I9z-nrk9cw0", "AI Agents vs. LLMs: Choosing the Right Tool for AI Tasks", "7:51"],
    ["w__y7508704", "Understanding AI Concepts: Machine Learning, Gen AI, NLP, & More", "6:21"],
    ["tE7e1w0XARk", "Escape the AI Graveyard: Fixing Data and Machine Learning Failures", "7:29"],
    ["ESBMgZHzfG0", "AI Periodic Table Explained: Mapping LLMs, RAG & AI Agent Frameworks", "16:51"],
    ["zt0JA5rxdfM", "AI Trends 2026: Quantum, Agentic AI & Smarter Automation", "11:39"],
    ["fB2JQXEH_94", "RAG vs Agentic AI: How LLMs Connect Data for Smarter AI", "10:01"],
    ["ZHCB09O6zUk", "A Brief History of AI: From Machine Learning to Gen AI to Agentic AI", "12:54"],
    ["RRKwmeyIc24", "What Is an AI Stack? LLMs, RAG, & AI Hardware", "9:06"],
    ["znF2U_3Z210", "Machine Learning Explained: A Guide to ML, AI, & Deep Learning", "10:39"],
    ["23PzNxw11jc", "MCP vs gRPC: How AI Agents & LLMs Connect to Tools & Data", "10:35"],
    ["rBlCOLfMYfw", "The Limits of AI: Generative AI, NLP, AGI, & What’s Next?", "19:51"],
    ["VSFuqMh4hus", "7 AI Terms You Need to Know: Agents, RAG, ASI & More", "11:04"],
    ["7j1t3UZA1TY", "MCP vs API: Simplifying AI Agent Integration with External Data", "13:11"],
    ["zYGDpG-pTho", "RAG vs Fine-Tuning vs Prompt Engineering: Optimizing AI Models", "13:10"],
    ["qYNweeDHiyU", "AI, Machine Learning, Deep Learning and Generative AI Explained", "10:01"],
    ["CiSaY2xl9V4", "Ten Everyday Machine Learning Use Cases", "7:07"],
    ["7a2s3_wkiWo", "Large Language Models: How Large is Large Enough?", "6:52"],
    ["7gMg98Hf3uM", "What Makes Large Language Models Expensive?", "19:20"],
    ["Gxc7pDDbn7U", "Generative AI: A Conversation with Malcolm Gladwell & Darío Gil", "29:18"],
    ["TabyC8otFY8", "AI and Large Language Models Boost Language Translation", "6:19"],
    ["XFZ-rQ8eeR8", "The 7 Types of AI - And Why We Talk (Mostly) About 3 of Them", "6:50"],
    ["Beh13Cd_QbY", "Machine Learning vs.  Deep Learning  vs.  Foundation Models", "7:27"],
    ["OThahaOga20", "How to Add AI to Your Apps Faster with Embedded AI", "7:35"],
    ["-dAmqHFWzyg", "Top 5 AI Myths", "6:58"],
    ["4RixMPF4xis", "AI vs Machine Learning", "5:49"],
    ["hfIUstzHs9A", "What are Generative AI models?", "8:47"],
    ["hdKYPxzeerU", "Artificial Intelligence  - Are We There Yet?", "7:08"],
    ["1I6bQ12VxV0", "NLP vs NLU vs NLG", "6:48"],
    ["8lo1s29ODj8", "Humans vs. AI: Who should make the decision?", "8:57"],
    ["Ce1m3Y0OMKA", "Artificial Intelligence vs. Augmented Intelligence", "5:52"],
    ["fLvJ8VdHLA0", "What is NLP (Natural Language Processing)?", "9:38"],
    ["9gGnTQTYNaE", "What is Machine Learning?", "8:23"],
    ["o9-ObGgfpEk", "What is a Chatbot?", "9:42"],
  ],
  "PLOspHqNVtKAC-FUNMq8qjYVw6_semZHw0": [
    ["F3hlZSZc6UI", "How AI Agents, LLMs & APIs Use Real-Time Data at the US Open", "9:46"],
    ["ZELPNFXJ4_o", "AI Model vs Agentic Harness: What Actually Drives AI", "8:30"],
    ["uhWFLmr7xao", "What Is AI Model Collapse? Why AI Could Forget Reality", "13:10"],
    ["uU1EP9_4qBU", "What Are Large Database Models? AI for SQL Data", "13:55"],
    ["DAlC8mL5ZlI", "Why AI Models Pause to Think: Test Time Compute Explained", "10:32"],
    ["J51oZYcNvP8", "What is Multimodal AI? How LLMs Process Text, Images, and More", "9:15"],
    ["wIXr22QTEHg", "LLM Compression Explained: Build Faster, Efficient AI Models", "11:23"],
    ["u57EnkQaUTY", "What is Prompt Caching? Optimize LLM Latency with AI Transformers", "9:06"],
    ["AVQzG2MY858", "LLM vs. SLM vs. FM: Choosing the Right AI Model", "14:09"],
    ["CNKGgOphAPM", "LLM‑D Explained: Building Next‑Gen AI with LLMs, RAG & Kubernetes", "5:17"],
    ["enLbj0igyx4", "What Are Large Reasoning Models (LRMs)? Smarter AI Beyond LLMs", "8:38"],
    ["dAE7OFm9oek", "Can You Trust an AI to Judge Fairly? Exploring LLM Biases", "7:32"],
    ["trfUBIDeI1Y", "LLM as a Judge: Scaling AI Evaluation Strategies", "6:09"],
    ["HdafI0t3sEY", "RAG vs. CAG: Solving Knowledge Gaps in AI Models", "16:00"],
    ["F8NKVhkZZWI", "What are AI Agents?", "12:29"],
    ["XctooiH0moI", "Build a Large Language Model AI Chatbot using Retrieval Augmented Generation", "2:53"],
    ["85RfazjDPwA", "Scaling AI Model Training and Inferencing Efficiently with PyTorch", "18:29"],
    ["fJ40w_2h8kk", "What is PyTorch? (Machine/Deep Learning)", "11:57"],
    ["QPQy7jUpmyA", "Why Are There So Many Foundation Models?", "5:14"],
    ["jcgaNrC4ElU", "Five Steps to Create a New AI Model", "6:56"],
    ["Cgiqx0pJuLo", "Open Source in Action with watsonx", "7:32"],
    ["OThahaOga20", "How to Add AI to Your Apps Faster with Embedded AI", "7:35"],
    ["5sLYAQS9sWQ", "How Large Language Models Work", "5:34"],
    ["zqv1eELa7fs", "Training AI Models with Federated Learning", "6:27"],
    ["S5AGN9XfPK4", "What is Back Propagation", "8:00"],
    ["T-w_5T-j-dA", "Large Language Models Are Zero Shot Reasoners", "7:47"],
    ["OejCJL2EC3k", "What is MLOps?", "6:55"],
    ["GE3JOFwTWVM", "What is Time Series Analysis?", "7:29"],
    ["i62czvwDlsw", "Gradient Descent Explained", "7:05"],
    ["W01tIRP_Rqs", "Supervised vs. Unsupervised Learning", "7:08"],
    ["7TqhmX92P6U", "What is Monte Carlo Simulation?", "4:35"],
    ["0RT2Q0qwXSA", "Overfitting, Underfitting, and Bad Data Are Ruining Your Predictive Models", "6:49"],
    ["1I6bQ12VxV0", "NLP vs NLU vs NLG", "6:48"],
    ["qiUEgSCyY5o", "What are Autoencoders?", "5:00"],
    ["ZXiruGOCn9s", "What are Transformers (Machine Learning Model)?", "5:51"],
    ["L3ynnRgpZwg", "What is an RBM (Restricted Boltzmann Machine)?", "6:06"],
    ["y7sXDpffzQQ", "What is a Knowledge Graph?", "5:36"],
    ["gkXX4h3qYm4", "What is Random Forest?", "5:21"],
    ["T7Wr7wVK5Wo", "Fluid vs. Crystallized Intelligence", "5:52"],
    ["jevuDDjFEsM", "Edge AI vs. Distributed AI", "15:56"],
    ["b61DPVFX03I", "What is LSTM (Long Short Term Memory)?", "8:19"],
    ["TpMIssRdhco", "What are GANs (Generative Adversarial Networks)?", "8:23"],
    ["QzY57FaENXg", "What are Convolutional Neural Networks (CNNs)?", "6:21"],
    ["fLvJ8VdHLA0", "What is NLP (Natural Language Processing)?", "9:38"],
    ["6dyrBRcC5KA", "Use AI-Powered Automation to Accelerate Auto Claims Processing", "2:01"],
  ],
  "PLOspHqNVtKAAsiohuZj1Bt4XpA3_bkS3c": [
    ["yu27PWzJI_Y", "What is Prompt Tuning?", "8:33"],
    ["r4kButlDLUc", "Risks of Large Language Models (LLM)", "8:26"],
    ["cfqtFvWOfg0", "Why Large Language Models Hallucinate", "9:38"],
    ["TabyC8otFY8", "AI and Large Language Models Boost Language Translation", "6:19"],
    ["T-w_5T-j-dA", "Large Language Models Are Zero Shot Reasoners", "7:47"],
    ["y9k-U9AuDeM", "Should You Use Open Source Large Language Models?", "6:40"],
    ["gZTQNb0NGjM", "Hypnotized AI and Large Language Model Security", "13:22"],
    ["o9-ObGgfpEk", "What is a Chatbot?", "9:42"],
    ["93l-2Usc08U", "Do Chatbots Need AI?", "5:17"],
    ["RTCaGwxD2uU", "How Chatbots Could Be 'Hacked' by Corpus Poisoning", "8:31"],
    ["Cgiqx0pJuLo", "Open Source in Action with watsonx", "7:32"],
    ["j-bmHSZUYlI", "3 Benefits of virtual assistants for Customer Service", "3:22"],
  ],
  "PLOspHqNVtKACJx_ue2EXC1MerohY_lLKO": [
    ["s4r5gXdSVPM", "The Rise of Generative AI for Business", "14:45"],
    ["fBR42OxjWaM", "Become a value creator with generative AI", "14:38"],
    ["1JzMSbcInxc", "Why foundation models are a paradigm shift for AI", "8:30"],
    ["odrD0OLPeiY", "Trust, transparency, and governance in the age of generative AI", "9:39"],
    ["_3-ZOKKo7II", "Putting AI to work for Customer Service", "11:24"],
    ["AINoTKMZSGI", "Putting AI to Work for Application Modernization", "7:59"],
    ["qtuzVc0N5o0", "Is data management the secret to generative AI?", "11:36"],
    ["c54qSfmTT5U", "Putting AI to Work for Marketing", "11:58"],
    ["MZmJTnjJd7Y", "Putting AI to Work for talent", "8:08"],
    ["C1ecR-sIE1A", "Select the right AI use case for your business", "3:41"],
    ["n0WapyCr0tk", "How responsible AI can prepare you for AI regulations", "9:12"],
    ["aqWXSShwGO0", "Choose the right AI model for your use case", "4:04"],
    ["FtYKoDomUp8", "From pilot to production: Driving ROI with genAI", "9:47"],
    ["xy1824BAljk", "AI Academy 2024 Trailer", "1:08"],
    ["vI_2LSc6NCg", "Achieving AI-readiness with hybrid cloud", "8:55"],
    ["4VCwKSaMOqY", "Putting AI to work in IT Operations", "3:57"],
    ["6-s_fUXP0FM", "Design a hybrid cloud infrastructure for and with AI", "9:10"],
    ["kNXOCsL9OF8", "Putting AI to work for Finance", "11:06"],
    ["anirI6Xtezs", "How business leaders budget for generative AI", "9:10"],
    ["dUWd2IFPQrM", "Put AI to work in supply chains", "10:31"],
    ["i0gaHvT6iWQ", "Reimagine business productivity with AI agents and assistants", "7:59"],
    ["qo1ko4HSLPw", "What's next for mainframes and AI?", "7:21"],
    ["HnFy1MU5w0k", "Building a data strategy for AI", "8:22"],
    ["TQjLFNpu4r8", "Put AI to work for Observability", "6:34"],
  ],
  "PLOspHqNVtKADe2YWKvnuqWbddubJZvQf0": [
    ["N3-zrhoBx6w", "What is the Dark Web? A Guide to the Dark Side of the Internet", "9:49"],
    ["qYNweeDHiyU", "AI, Machine Learning, Deep Learning and Generative AI Explained", "10:01"],
    ["vKPGZHoHX8k", "How Hackers Steal Passwords: 5 Attack Methods Explained", "13:07"],
    ["5sLYAQS9sWQ", "How Large Language Models Work", "5:34"],
    ["4RixMPF4xis", "AI vs Machine Learning", "5:49"],
    ["EDb37y_MhRw", "Generative vs Agentic AI: Shaping the Future of AI Collaboration", "7:19"],
    ["VSFuqMh4hus", "7 AI Terms You Need to Know: Agents, RAG, ASI & More", "11:04"],
    ["7j1t3UZA1TY", "MCP vs API: Simplifying AI Agent Integration with External Data", "13:11"],
    ["UabBYexBD4k", "Is RAG Still Needed? Choosing the Best Approach for LLMs", "11:10"],
    ["gl1r1XV0SLw", "What is a Vector Database? Powering Semantic Search & AI Applications", "9:49"],
    ["CMHL1bPtQdI", "Zero-Click Attacks: AI Agents and the Next Cybersecurity Challenge", "15:06"],
    ["mUw27wG7uFA", "AI Simplified: 6 Concepts You Need to Know About Modern AI", "8:49"],
    ["eur8dUO9mvE", "What is MCP? Integrate AI Agents with Databases & APIs", "3:46"],
    ["zYGDpG-pTho", "RAG vs Fine-Tuning vs Prompt Engineering: Optimizing AI Models", "13:10"],
    ["HdafI0t3sEY", "RAG vs. CAG: Solving Knowledge Gaps in AI Models", "16:00"],
    ["YGgNBcIgI4s", "What Is Jev? The AI Model That Doesn't Generate Text", "15:03"],
    ["rBlCOLfMYfw", "The Limits of AI: Generative AI, NLP, AGI, & What’s Next?", "19:51"],
    ["mtiOK2QG9Q0", "The 7 Skills You Need to Build AI Agents", "14:37"],
    ["XN3xNJvWXsc", "Essential Skills for Becoming an AI Engineer: RAG, AI Agents, & More", "10:55"],
    ["zMahtD8TIwc", "Do VPNs Really Protect Privacy? Data & Cybersecurity Insights", "14:17"],
    ["mViFYTwWvcM", "Spec-Driven Development: AI Assisted Coding Explained", "9:00"],
    ["Lg-meK5IU8Q", "What AI Agent Skills Are and How They Work", "12:25"],
    ["zt0JA5rxdfM", "AI Trends 2026: Quantum, Agentic AI & Smarter Automation", "11:39"],
    ["RRKwmeyIc24", "What Is an AI Stack? LLMs, RAG, & AI Hardware", "9:06"],
    ["2jU-mLMV8Vw", "Cybersecurity Trends in 2026: Shadow AI, Quantum & Deepfakes", "20:29"],
    ["k7PvscqGD24", "AI & Education: Generative AI & the Future of Critical Thinking", "16:02"],
    ["L7FF8Zgab3M", "What is OpenClaw? Inside AI Agents, LLMs and the Agentic Loop", "11:35"],
    ["RVF6NVnJvd8", "What Is Quishing? How Hackers Use QR Codes to Steal Your Data", "8:43"],
    ["vD0E3EUb8-8", "Context Engineering vs. Prompt Engineering: Smarter AI with RAG & Agents", "7:52"],
    ["ESBMgZHzfG0", "AI Periodic Table Explained: Mapping LLMs, RAG & AI Agent Frameworks", "16:51"],
    ["0tHb6U2604g", "AI ATTACKS! How Hackers Weaponize Artificial Intelligence", "18:36"],
    ["o0gkdZBtwEg", "How KV Cache Speeds Up LLMs for Faster AI Models on GPUs", "11:15"],
    ["X4FVEEegCbk", "Skills vs MCP vs RAG vs Memory: What AI Agents Need to Know", "9:11"],
    ["Ts42JTye-AI", "10 Use Cases for AI Agents: IoT, RAG, & Disaster Response Explained", "9:12"],
    ["JB2P5Gk23VI", "RAG's Evolution: From Simple Retrieval to Agentic AI", "8:48"],
    ["ZELPNFXJ4_o", "AI Model vs Agentic Harness: What Actually Drives AI", "8:30"],
    ["kyJ1vd7yEPc", "AI Is Exposing Your Data: An AI Security Problem You Can't See", "11:29"],
    ["-W2JdSl1v48", "Is Fine-Tuning Still Needed? LLMs, RAG, & LoRA", "10:52"],
    ["goU9VIXA8II", "MCP vs Skills: Which Is Right for Your AI Agent and LLMs?", "8:03"],
    ["X0UI0O8YzJM", "How Developers Secure AI-Generated Code: 5 Security Best Practices", "11:28"],
    ["l-QPwk_f4eE", "Why AI Makes the Humanities More Important Than Ever", "14:32"],
  ],
  "PLOspHqNVtKADc8E1JLd_kBBPdEBDdmwsR": [
    ["VSFuqMh4hus", "7 AI Terms You Need to Know: Agents, RAG, ASI & More", "11:04"],
    ["UabBYexBD4k", "Is RAG Still Needed? Choosing the Best Approach for LLMs", "11:10"],
    ["RRKwmeyIc24", "What Is an AI Stack? LLMs, RAG, & AI Hardware", "9:06"],
    ["ESBMgZHzfG0", "AI Periodic Table Explained: Mapping LLMs, RAG & AI Agent Frameworks", "16:51"],
    ["X4FVEEegCbk", "Skills vs MCP vs RAG vs Memory: What AI Agents Need to Know", "9:11"],
    ["fB2JQXEH_94", "RAG vs Agentic AI: How LLMs Connect Data for Smarter AI", "10:01"],
    ["JB2P5Gk23VI", "RAG's Evolution: From Simple Retrieval to Agentic AI", "8:48"],
    ["kyJ1vd7yEPc", "AI Is Exposing Your Data: An AI Security Problem You Can't See", "11:29"],
    ["X95MFcYH1_s", "MCP vs. RAG: How AI Agents & LLMs Connect to Data", "8:32"],
    ["CAKGKkWf0tI", "Anatomy of AI Agents: Inside LLMs, RAG Systems, & Generative AI", "10:29"],
    ["pN-LfxNFiTc", "How RAG, GraphRAG, and Context Engineering Improve AI Performance", "10:50"],
    ["7HSSR1n8dgc", "ADK vs RAG: How to Choose the Right AI Stack", "6:31"],
    ["anLahYrEFiQ", "What is Multimodal RAG? Unlocking LLMs with Vector Databases", "11:13"],
    ["vRZNJWw78BQ", "What Is Chunkless RAG? How Docling & AI Agents Navigate Documents", "7:00"],
    ["qreMmsOY86A", "What is OpenRAG? Unlocking the Future of RAG in Generative AI", "7:58"],
    ["r0Dciuq0knU", "Top 3 RAG Retrieval Strategies: Sparse, Dense, & Hybrid Explained", "8:29"],
    ["81FbpXpfxTc", "AI Models as a Service: Powering Agentic AI, Privacy, & RAG", "10:31"],
    ["CNKGgOphAPM", "LLM‑D Explained: Building Next‑Gen AI with LLMs, RAG & Kubernetes", "5:17"],
    ["egJAqyS9CB8", "Llama Stack: Kubernetes for RAG & AI Agents in Generative AI", "6:37"],
    ["rrQHnibpXX8", "Unlock Better RAG & AI Agents with Docling", "6:50"],
    ["xc63tFIIfeA", "Why RAG Solutions Fail with Complex Documents & Vector Databases", "7:46"],
    ["sMQ5R92F86o", "Unlocking Smarter AI Agents with Unstructured Data, RAG & Vector Databases", "6:41"],
    ["RNYdP6CYrOw", "How AI, RAG, and Agents Transform Mainframe Operations", "6:53"],
    ["l9LfC98tE_4", "Building Trustworthy AI Agents with Hybrid RAG", "4:25"],
  ],
  "PLOspHqNVtKAB6AzNie7BrFhbg4dv4Gfz8": [
    ["F8NKVhkZZWI", "What are AI Agents?", "12:29"],
    ["IivxYYkJ2DI", "AI Agents and AI Assistants: A Contrast in Function", "6:49"],
    ["EDb37y_MhRw", "Generative vs Agentic AI: Shaping the Future of AI Collaboration", "7:19"],
    ["Ts42JTye-AI", "10 Use Cases for AI Agents: IoT, RAG, & Disaster Response Explained", "9:12"],
    ["_pEEJu-2KKM", "LLMs and AI Agents: Transforming Unstructured Data", "20:21"],
    ["wiU7VEvi1LM", "How will AI Agents Manage Identity & Build Trust in Complex Systems", "14:04"],
    ["X3XJeTApVMM", "What Are Orchestrator Agents? AI Tools Working Smarter Together", "4:24"],
    ["gUrENDkPw_k", "How to Build a Multi Agent AI System", "19:06"],
    ["446x7GqXdaA", "AI Agents Best Practices: Monitoring, Governance, & Optimization", "9:11"],
    ["j_Q1cL6Cog4", "AI Agents in Action: How Research Agents Solve Complex Problems", "9:36"],
    ["T_c48yxTNuM", "AI Agents for Real-Time Lead Generation: Tools, Frameworks, & LLMs", "18:43"],
    ["Yq29bZ8Hlrc", "Optimize RAG with AI Agents & Vector Databases", "32:57"],
    ["aQuCTWhiiPg", "Enhancing AI Agents Through Fine Tuning & Model Customization", "9:26"],
    ["1ax9rz3kSK8", "ChatGPT Agents", "0:52"],
    ["cyMdBK8oEYc", "Content-Aware Storage: Powering AI Agents & Assistants with RAG", "5:20"],
    ["eQN0mNC37UU", "AI Agents & LLMs: Real-Time IT Issue Prediction & Prevention", "12:40"],
    ["5Igexz7kzMo", "AI Agents: Transforming Anomaly Detection & Resolution", "11:45"],
    ["4-FH09AMsp0", "AI Agents vs Mixture of Experts: AI Workflows Explained", "9:28"],
    ["yJkCuEu3K68", "Explainable AI: Demystifying AI Agents Decision-Making", "6:51"],
    ["D9fp2OVeAIo", "Are AI Agent Identities Really Unique? AI's Role in Digital Workflows", "12:08"],
    ["mRkJTXDromw", "Building Decision Agents with LLMs & Machine Learning Models", "24:43"],
    ["Tud9HLTk8hg", "A2A Protocol (Agent2Agent) Explained: How AI Agents Collaborate", "8:52"],
    ["Wtpwva8t1vs", "Designing AI Decision Agents with DMN, Machine Learning & Analytics", "20:40"],
    ["2ihEirLXeas", "AI Agents + LLM Reasoning: Transforming Autonomous Workflows", "13:58"],
    ["R43Q0nIXa1Q", "Python SDK Meets AI Agents: Automating Data Pipelines with LLMs", "8:58"],
    ["Ons1Fv3IE4U", "Orchestrator Agents & MCP: How AI Agents Drive Automation", "6:42"],
    ["2j26a5dmCnI", "The Power of AI Agents and Agentic AI Explained", "10:24"],
    ["ZeZozy3lsJg", "Is this the YEAR or DECADE of AI Agents & Agentic AI?", "13:25"],
    ["yKPAwTF1SGY", "Preparing IT for AI Agents: How MCP Shapes the Future of AI", "20:51"],
    ["sWH0T4Zez6I", "Multi Agent Systems Explained: How AI Agents & LLMs Work Together", "7:57"],
    ["bwvfdFWR1RI", "How to Use Agentic AI: LLMs, AI Agents & Prompt Engineering in Action", "6:32"],
    ["CAKGKkWf0tI", "Anatomy of AI Agents: Inside LLMs, RAG Systems, & Generative AI", "10:29"],
    ["-Tz_FWVYgnM", "Build Private Agentic AI Flows with LLMs for Data Privacy", "7:04"],
    ["rrQHnibpXX8", "Unlock Better RAG & AI Agents with Docling", "6:50"],
    ["2P9DOtg4gP4", "Federated Learning & Encrypted AI Agents: Secure Data & AI Made Simple", "5:01"],
    ["E_yPUsCpoC8", "Securing & Governing Autonomous AI Agents: Risks & Safeguards", "11:43"],
    ["UMYtqHptYvA", "Guide to Architect Secure AI Agents: Best Practices for Safety", "13:45"],
    ["BMDFPOyezH4", "A2A vs MCP: AI Agent Communication Explained", "11:46"],
    ["wh489_XT5TI", "What Are Hierarchical AI Agents? Solving Context & Task Challenges", "10:36"],
    ["cmEJ-5zYKHA", "Why AI Agents Need A Human in the Loop Now", "7:27"],
    ["i36R5orEXYQ", "4 Ways AI Agents Should Behave for Smarter Systems", "13:24"],
    ["lUQ2NKkCW_Q", "Agentic Trust: Securing AI Interactions with Tokens & Delegation", "12:50"],
    ["kqj22mWIdjU", "Building a Team of AI Agents: Roles, Feedback, & Teamwork Explained", "9:59"],
    ["Lg-meK5IU8Q", "What AI Agent Skills Are and How They Work", "12:25"],
    ["IVGjBxqygmI", "Why AI Agents Need an Operating System", "12:21"],
    ["kYkZI3oj2W4", "Multi AI Agent Systems: When One AI Brain Isn’t Enough", "10:55"],
    ["BacJ6sEhqMo", "The Four Types of Memory Every AI Agent Needs", "10:41"],
    ["SbrEk_tXZaE", "Why AI Agents Break Zero Trust at the Last Mile", "13:15"],
    ["k5jYwyhDMxA", "5 AI Agent Terms You Need to Know", "11:07"],
    ["bNRhppHct54", "Understanding AI Agent Hallucination in AI Systems", "10:51"],
    ["fCHe_fOqlYA", "Building AI Agent Systems and Scaling Challenges in Agentic AI", "13:05"],
    ["SVAwzodyFUo", "How to Manage Your AI Before It Makes the Wrong Decision", "8:50"],
    ["PjrXaC5UsIw", "What Is Agentic Coding? How AI Agents Modernize Code", "10:21"],
    ["goU9VIXA8II", "MCP vs Skills: Which Is Right for Your AI Agent and LLMs?", "8:03"],
    ["nVImVgKpoOY", "LLM & AI Agent Benchmarks vs Reality: Why AI Applications Break", "15:01"],
    ["i1ZmNUbRGD4", "AI Agents vs Business Rules: Which Should Make Decisions?", "10:25"],
    ["qYNs80FKIVc", "5 Best Practices for Building AI Agent Skills", "13:22"],
    ["BHGTA6ZEls4", "5 Ways to Connect AI Agents to Tools: From APIs to MCP", "11:28"],
    ["X4FVEEegCbk", "Skills vs MCP vs RAG vs Memory: What AI Agents Need to Know", "9:11"],
    ["kyJ1vd7yEPc", "AI Is Exposing Your Data: An AI Security Problem You Can't See", "11:29"],
    ["jRMbbRdju7Q", "When Should AI Systems Use Super Agents?", "11:26"],
    ["F3hlZSZc6UI", "How AI Agents, LLMs & APIs Use Real-Time Data at the US Open", "9:46"],
    ["YGgNBcIgI4s", "What Is Jev? The AI Model That Doesn't Generate Text", "15:03"],
  ],
  "PLOspHqNVtKAAY8UCxA15eIK3lgE9BLc4n": [
    ["7j1t3UZA1TY", "MCP vs API: Simplifying AI Agent Integration with External Data", "13:11"],
    ["eur8dUO9mvE", "What is MCP? Integrate AI Agents with Databases & APIs", "3:46"],
    ["X4FVEEegCbk", "Skills vs MCP vs RAG vs Memory: What AI Agents Need to Know", "9:11"],
    ["BMDFPOyezH4", "A2A vs MCP: AI Agent Communication Explained", "11:46"],
    ["g9JIUM0MHgQ", "CLI vs MCP: How AI Agents Choose the Right Tool for the Job", "14:06"],
    ["goU9VIXA8II", "MCP vs Skills: Which Is Right for Your AI Agent and LLMs?", "8:03"],
    ["X95MFcYH1_s", "MCP vs. RAG: How AI Agents & LLMs Connect to Data", "8:32"],
    ["TjvT9sI5mLE", "What Is Agentic Storage? Solving AI’s Limits with LLMs & MCP", "7:46"],
    ["23PzNxw11jc", "MCP vs gRPC: How AI Agents & LLMs Connect to Tools & Data", "10:35"],
    ["BedAaB1RKgE", "MCP vs ADK: How Modern AI Agents Connect and Work Together", "14:11"],
    ["l93LrDpIJGY", "MCP in Action: Revolutionizing AI Agent Integration", "8:00"],
    ["yKPAwTF1SGY", "Preparing IT for AI Agents: How MCP Shapes the Future of AI", "20:51"],
    ["xz00BbW1z6M", "What is Langflow? Build AI Workflows with Python, Gen AI, & MCP Tools", "6:18"],
    ["pUUzXimhUuA", "AI Search Agents Redefined: Agentic Research, MCP, & Tool Calling", "10:00"],
    ["Ons1Fv3IE4U", "Orchestrator Agents & MCP: How AI Agents Drive Automation", "6:42"],
    ["Gh1E9VgXZWs", "Bridging Design Systems and Code with MCP and AI Agents", "3:47"],
  ],
  "PLOspHqNVtKADqC3pf-SjB23mtqJbmwsWw": [
    ["mViFYTwWvcM", "Spec-Driven Development: AI Assisted Coding Explained", "9:00"],
    ["4wMRXmLpdA8", "AI in the SDLC: Rethinking AI Coding Tools & AI Agents", "9:28"],
    ["X0UI0O8YzJM", "How Developers Secure AI-Generated Code: 5 Security Best Practices", "11:28"],
    ["DgXV8QSlI4U", "What is AI Technical Debt? Key Risks for Machine Learning Projects", "13:33"],
    ["FheRqx7DjbU", "Goodbye Tokenmaxxing: From AI Usage to Agentic AI Outcomes", "8:26"],
    ["qYNs80FKIVc", "5 Best Practices for Building AI Agent Skills", "13:22"],
    ["c57vAe-mMLo", "How AI Is Changing Code Reviews & Software Development", "14:09"],
    ["Y68FF_nUSWE", "What Is Vibe Coding? Building Software with Agentic AI", "7:01"],
    ["J0zbWsutyA8", "What Is RAD? Why It Matters in the Age of AI Coding", "10:53"],
    ["PjrXaC5UsIw", "What Is Agentic Coding? How AI Agents Modernize Code", "10:21"],
    ["FgaBdwSvOGM", "Agentic Engineering vs Software Engineering: Beyond Vibe Coding", "10:46"],
    ["GRYZR2R20FI", "Code Quality in the Age of AI: Why Great Code Isn't Enough", "13:54"],
    ["zAe-sau06io", "How AI Coding Agents Understand Your Codebase & Developer Tools", "6:54"],
    ["9LfJq4xXifg", "6 Ways to Enhance Developer Productivity with AI", "12:53"],
    ["fWZylhIHF9w", "What Is an AI IDE? How AI Is Changing Developer & Coding Tools", "8:47"],
    ["MTmhgIVhpag", "What Is AI Pair Programming? AI Coding Tools for Developers", "7:16"],
    ["f84XbvASkk4", "What Is AI Code Refactoring? Agentic AI & Safe Code Changes", "11:36"],
    ["0-YCleDw-Po", "What Is AI Code Review? Fixing Slow PRs & Broken Workflows with AI", "10:53"],
    ["oanQrXEiCy4", "What is an AI Code Generator? LLM Coding, Productivity, & Risk", "12:48"],
    ["lYDkcC9DDaM", "Code Risk Intelligence: Securing AI Coding at Scale in Real Time", "5:48"],
    ["5RtmQSKKQo8", "IDE vs CLI: What Every DevOps Engineer Should Know", "9:38"],
  ],
  "PLOspHqNVtKACI0uR7Oa-bkWbtTufpJNhi": [
    ["OuBxnfPA15g", "How to Self-Host an LLM: Local AI Inference with vLLM", "11:06"],
    ["Lj8n3DlqtPk", "How to Debug UI Bugs Faster With AI Coding Assistants", "4:56"],
    ["-BnIfH2J50I", "How Context Engineering Improves AI Coding Agents", "9:20"],
    ["MjrTcjz12LM", "Build an Agentic Data Layer with Astra DB Using Python", "10:19"],
    ["o7AzbObl8Tk", "Agentic Coding + Planning: Why Specs Matter More Than Code", "14:25"],
    ["KRmln6u9QNk", "CPU vs GPU SQL: Boost Presto Query Performance Fast", "8:24"],
    ["k2LLUKj6piE", "Stop Vibe Coding: Build Better Apps with Spec Kit", "13:58"],
    ["kvBvMEQhSMU", "How to Use Astra DB Data API in C# (.NET)", "15:40"],
    ["knIuMPO-IUA", "How to Shift DevOps Left with Terraform, MCP & LLMs", "8:32"],
    ["MEOh5fdBWWs", "RAG vs Direct Context: Choosing the Right LLM Strategy in Practice", "12:30"],
    ["Y0b1TANWZ-Y", "Extract Insights from Videos with Docling + OpenRAG", "10:49"],
    ["AXrmMo3GzT0", "Unlocking Video Knowledge with Docling: Transcribe & Query with AI", "6:49"],
    ["Mdbq1dD6Yuo", "Meet Bob: An AI-Powered IDE for Modern Software Development", "8:46"],
    ["WozA_qHEAqo", "BeeAI Framework: Extending LLMs with Tools, RAG, & AI Agents", "6:35"],
    ["_1uFtDfqapo", "Build a Local LLM App in Python with Just 2 Lines of Code", "14:04"],
    ["pYax2rupKEY", "How to Choose Large Language Models: A Developer’s Guide to LLMs", "6:57"],
    ["Yq29bZ8Hlrc", "Optimize RAG with AI Agents & Vector Databases", "32:57"],
    ["EyYJI8TPIj8", "How to Build an MCP Server for LLM Agents: Simplify AI Integration", "15:06"],
    ["uxE8FFiu_UQ", "Run AI Models Locally with Ollama: Fast & Simple Deployment", "6:00"],
    ["U2TP0pTsSlw", "Build a Text-to-SQL Agent for Smarter Database Queries", "26:18"],
    ["u6qDSFxY4iw", "Build a LangGraph AI Agent to Transcribe & Summarize YouTube Videos", "25:19"],
    ["txosy9PzAKg", "Build an AI Chat App with JavaScript and Next.js", "35:24"],
    ["MOOPuizuf6o", "Time Series Forecasting with Lag Llama", "6:48"],
    ["GyIaXarpq9w", "Content Extraction using Large Language Models & JavaScript", "5:03"],
    ["pu3-PeBG0YU", "Fine Tuning Large Language Models with InstructLab", "8:01"],
    ["1GWac3Vi5uo", "AI Tools for Developers: Streamlining Code with Generative Models", "6:11"],
    ["PoqGrCscJ7k", "Confusion to Clarity: Mastering Confusion Matrix in Machine Learning", "15:15"],
    ["2hB3XzfpGtI", "Code, Generate, Repeat: Building a Full-Stack Generative AI Application", "1:04:55"],
    ["Y1PaM3edYoI", "Create Advanced AI Agents with LangChain and RAG Techniques", "6:48"],
    ["cjCYcTPryw8", "Build AI Function Calling with LangChain & Advanced AI Models", "6:37"],
    ["C-pZXA6Te_o", "Building LLM Agent with IBM Bee Agent Framework", "4:18"],
    ["LpKGm1jJXv4", "Setting up Retrieval Augmented Generation (RAG) in 3 Steps", "2:51"],
    ["c7ZAceXakIE", "Connecting Large Language Models to Chatbots in Under 10 Minutes", "5:36"],
    ["gUrENDkPw_k", "How to Build a Multi Agent AI System", "19:06"],
  ],
  "PLOspHqNVtKADcG4vf83D97cKUrs5WdXXR": [
    ["eZ1NizUx9U4", "AI isn’t digital transformation, and leaders need to understand why", "36:58"],
    ["9vGXLQW9xxU", "AI is powering the next generation of intelligent robots", "7:44"],
    ["DjtFW4v9A_c", "AI-powered robotics: Transforming industrial workflows", "21:22"],
    ["jazothuFVss", "Scaling AI for seamless customer experiences in retail", "6:03"],
    ["IwXYQ9WVJ5Y", "Inside Tractor Supply Company’s AI-powered operations", "24:51"],
    ["b3faiqOVTsQ", "AI: More than just productivity", "8:35"],
    ["1R0h86_X6nI", "The future of work lies in adopting employee-centric AI", "33:14"],
    ["Nl84PbWJ5XU", "When data centers grow, power must too", "10:01"],
    ["1ilygv9mOs8", "Why AI energy consumption should be on every business leader’s radar", "21:48"],
    ["toIgVExnwKc", "The key to AI success is knowing how to communicate", "7:03"],
    ["RNauzb5sA7s", "Decision intelligence powers smarter choices", "34:05"],
    ["YVARXkj6FOU", "Break free from silos with an all-in-one observability solution", "4:15"],
    ["vWTiijirvas", "Where traditional monitoring ends, AI-powered observability begins", "28:43"],
    ["X0jmwBlwrtA", "AI in real estate: Redfin’s new approach to home search", "3:54"],
    ["HYcXxm_Nh3c", "Buy and rent smarter with Redfin’s AI-driven real estate solutions", "17:52"],
    ["zUE_wh8Hay0", "AI agents: Not just faster but smarter", "11:16"],
    ["SgQMB-quTZY", "Using AI agents to transform your business at scale", "45:03"],
    ["fwiTAefJ4BI", "Spend less time, drive more sales with AI", "5:52"],
    ["vcEYP4enjaA", "AI built for sales: From pipeline generation to proposal creation", "29:23"],
    ["Z_Hx3RM7kNQ", "AI model training for smarter investment decisions", "3:52"],
    ["BVyiyd7tXo4", "How is AI revolutionizing financial services? Ron Insana explains.", "35:47"],
    ["8BQOw4cJ95s", "Agentic AI: Not just for greater efficiency but for higher ROI, too", "3:09"],
    ["Oo7WXs9UBno", "Transforming HR with agentic AI: Insights from IBM's client zero story", "29:23"],
    ["L0kYpMduz68", "The global average cost of a data breach", "5:58"],
    ["aD3VFjHjmLU", "Agentic AI: The emerging challenge in cybersecurity", "27:39"],
    ["R-ndBZzLxJA", "2025 Masters insights: Expert Jim “Bones” Mackay talks data and strategy", "21:20"],
    ["H-42uH642WI", "The women pioneering mainframes and AI", "26:29"],
    ["fbmNwM0TCqI", "Redefining marketing automation and personalization with generative AI", "40:09"],
    ["PJmYF-DTqEs", "How the Mayo Clinic's AI medicine app helps in stroke prevention", "27:18"],
    ["pxlAhUinl9o", "AI Realism with NE-YO and Ed Ulbrich: How AI affects artists, from IP to CGI", "30:28"],
    ["8P0tYXWiGds", "Gen AI for Good with James Hodson: Using AI to create a better tomorrow, today", "26:07"],
    ["VCA7wdZBuUE", "Change Agents with Ethan Mollick: How AI agents will reinvent productivity", "18:13"],
    ["HZYBj-zeUlY", "Hacking generative AI: Limiting security risk in the age of AI", "22:28"],
    ["BmajUTU3gGU", "AI Pilots to Progress: The lowdown on what makes AI projects successful", "36:51"],
    ["bdUqke_km3s", "Leaders v. learners: It all comes down to AI accessibility with Reshma Saujani", "19:07"],
    ["xerfuLpaApk", "Can you afford gen AI?", "21:25"],
    ["348242wb1-E", "Not just a chatbot: Build virtual agents that are actually helpful with gen AI", "32:42"],
    ["MmgdcWA3bcs", "Rewriting the future: how devs are driving gen AI", "15:32"],
    ["b0brvO-rrMI", "Modernizing code with AI Code Assistants", "21:47"],
    ["1FR5xIOknY4", "Use generative AI to help save people from screaming “representative”", "18:32"],
    ["V-zTsDVqnfQ", "The human side of HR — Fostering genuine connections with AI", "21:40"],
    ["FVXzkUCSu_U", "Scale your tech with a dynamic duo — AI and hybrid cloud", "22:25"],
    ["DGO60Zrdle8", "The art of delegating to AI: Using AI agents and chatbots to do the boring work", "19:44"],
    ["Vo5ifVY_Qrk", "AI in Action Podcast Trailer", "1:08"],
  ],
  "PLOspHqNVtKADin6JGozvzSvUQFTQRdum-": [
    ["OvjccOrr-iw", "What Is the AI Security Trilemma? Smart, Fast, or Secure AI?", "9:03"],
    ["K68sqG18270", "The Promptware Kill Chain: How Prompt Injection Becomes AI Malware", "10:48"],
    ["UE_vuadQrJ0", "AI That’s Too Dangerous For You? What we learned from S.A.T.A.N", "12:59"],
    ["7qZH3D7u-z8", "OpenClaw Security Risks: 6 Dangers of Autonomous AI Agents", "14:46"],
    ["SbrEk_tXZaE", "Why AI Agents Break Zero Trust at the Last Mile", "13:15"],
    ["lUQ2NKkCW_Q", "Agentic Trust: Securing AI Interactions with Tokens & Delegation", "12:50"],
    ["soFWS8NBcSU", "Top 10 Security Risks in AI Agents Explained", "8:59"],
    ["gUNXZMcd2jU", "OWASP's Top 10 Ways to Attack LLMs: AI Vulnerabilities Exposed", "25:12"],
    ["RKeW4Xd9V9E", "2026 Threat Intelligence Index: Ransomware, AI, & Emerging TTP Risks", "6:21"],
    ["SAYmsKxNDF4", "Understanding AI Agent Security: Safeguard LLM Systems Effectively", "8:46"],
    ["UMYtqHptYvA", "Guide to Architect Secure AI Agents: Best Practices for Safety", "13:45"],
    ["xHJ0_Vm7lK8", "AI Privilege Escalation: Agentic Identity & Prompt Injection Risks", "14:35"],
    ["d8d9EZHU7fw", "Securing AI Agents with Zero Trust", "13:33"],
    ["E_yPUsCpoC8", "Securing & Governing Autonomous AI Agents: Risks & Safeguards", "11:43"],
    ["5ZA1lTxTH3c", "Securing AI Agents: How to Prevent Hidden Prompt Injection Attacks", "10:08"],
    ["2jU-mLMV8Vw", "Cybersecurity Trends in 2026: Shadow AI, Quantum & Deepfakes", "20:29"],
    ["IaJ2jXmljmM", "Agentic AI Meets Shadow AI : Zero Trust Security for AI Automation", "16:00"],
    ["0tHb6U2604g", "AI ATTACKS! How Hackers Weaponize Artificial Intelligence", "18:36"],
    ["CMHL1bPtQdI", "Zero-Click Attacks: AI Agents and the Next Cybersecurity Challenge", "15:06"],
    ["4QXtObc61Lw", "Security & AI Governance: Reducing Risks in AI Systems", "15:10"],
    ["LyfG7SGRiZA", "Protecting Data in AI: Strategies for Security & Governance", "15:20"],
    ["dibZ1itSvM4", "What is LLMJacking? The Hidden Cloud Security Threat of AI Models", "7:21"],
    ["rLms76Q8bS4", "Autonomous Revolution: The Intersection of AI, Cyber Security, and Connected Cars", "13:01"],
    ["gZTQNb0NGjM", "Hypnotized AI and Large Language Model Security", "13:22"],
  ],
  "PLOspHqNVtKABEKVgWGrf6_x6OQYnYnCiM": [
    ["jRMbbRdju7Q", "When Should AI Systems Use Super Agents?", "11:26"],
    ["3G6AVkp4Rf0", "Why Risk Should Determine Your AI Architecture", "8:36"],
    ["4_LIxSjc3H0", "Decode Black Boxes with Explainable AI: Building Transparent AI Agents", "7:06"],
    ["5hK7pQsvpy0", "Building an AI Agent Governance Framework: 5 Essential Pillars", "10:04"],
    ["l9LfC98tE_4", "Building Trustworthy AI Agents with Hybrid RAG", "4:25"],
    ["446x7GqXdaA", "AI Agents Best Practices: Monitoring, Governance, & Optimization", "9:11"],
    ["OejCJL2EC3k", "What is MLOps?", "6:55"],
    ["r4kButlDLUc", "Risks of Large Language Models (LLM)", "8:26"],
    ["DK7w9-DGRO0", "Culture, Trust, and AI", "7:10"],
    ["aGwYtUzMQUk", "What is AI Ethics?", "6:10"],
  ],
  "PLOspHqNVtKADvnJYHm3HButDlWykOTzlP": [
    ["oBdLhD5nPYw", "OpenAI cancels Astra release, Sonnet 5.5 & what Meta Muse means for work", "31:51"],
    ["O4n1jtWzt30", "New frontier AI models, TypeSafe’s Jev AI, & NASA’s IBM collab", "39:24"],
    ["DtKEgRuq_00", "Pacing the AI frontier, IBM Granite 4.2 & Meta’s Muse assistant", "38:47"],
    ["XPReiOKCzFI", "OpenAI talks GPT-6 Astra and Millenium Prize, researchers create WeWorm exploit & IBM’s US Open app", "33:07"],
    ["W3iQbl5R_Jk", "Anthropic reveals hardware specs and Claude updates, OpenAI talks security, and Runway's new model", "34:47"],
    ["QxVS86cDpho", "IBM’s mainframe chip collab, NVIDIA’s Poolside deal & Ox Alpha’s reveal", "30:59"],
    ["8LNH7TxvD14", "Stripe buys OpenRouter, Ramp’s AI Index & IBM’s OpenAI deal", "35:52"],
    ["FVXDXi4es8E", "IBM’s cloud collab, Meta’s Muse Glimmer & OpenAI’s upcoming Astra model", "36:33"],
    ["W0wXevMkdMM", "Anthropic’s sandbox breach, EU’s AI transparency push and DeepSeek’s cost-cutting model", "40:22"],
    ["yb8Chvj--3c", "AI Security Costs Rise: Cost of a Data Breach Report & Claude Opus 5", "37:37"],
    ["7eCM7jsfbeA", "Hugging Face breach: OpenAI’s model breaks containment", "47:47"],
    ["8rGYGFmytQs", "Thinking Machines Lab drops Inkling & Meta’s Muse Spark 1.1", "39:02"],
    ["WHFLWrnFc1E", "Reddit cracks down on AI slop & the future of AI compute", "46:04"],
    ["tV5zXS78HzU", "GPT-5.6 Sol, FIFA AI & Wall Street’s AI nerves", "40:31"],
    ["d-hJa-yDJmQ", "New AI models, token minimization and IBM’s new sub-1nm chip", "51:02"],
    ["SvBheXuKY8s", "Microsoft’s new AI models & bots dominate the internet", "39:42"],
    ["aByPOYCEH6I", "Claude Fable 5 & Apple’s NVIDIA deal", "35:02"],
    ["EKULOf_Cy0w", "The future of software engineering, tokenmaxxing and AI in higher education", "45:51"],
    ["wVdivlahcm0", "Agent control planes & OpenAI model solves Erdős", "45:52"],
    ["1h6e5MFg9I0", "AI at college graduations and why Claude blackmails", "50:26"],
    ["YCWwh70FZtQ", "AI skills security, Open AI Deployment Company & zero days", "39:32"],
    ["YHKXflgkHak", "Live from Think 2026: AI operating model, VC funding & CAIO evolution", "29:47"],
    ["Zk3FX8ZXa-s", "Granite 4.1, IBM Bob & building a quantum ecosystem", "47:59"],
    ["vCP7C8CVw28", "Apple’s new CEO & how AI understands intent", "40:23"],
    ["Z_L5KO_GW4o", "Claude Opus 4.7, Apple’s AI glasses and Allbirds AI pivot", "53:05"],
    ["Yae74guiqq8", "Claude Mythos, Project Glasswing and AI cybersecurity risks", "49:26"],
    ["DW0jRLG3beU", "SpaceX IPO & AI data centers in space", "38:22"],
    ["OMpD6x5FSfs", "AI agent adoption: From scientists to CFOs", "40:01"],
    ["Ce_p69dV1jw", "NVIDIA NemoClaw, OpenAI’s pivot and Shopify agents", "47:41"],
    ["MmPtJ7TEkm8", "AI code security: Codex agents & crypto mining", "49:32"],
    ["iXAgtR-DO3I", "Inside Perplexity Computer’s agent platform", "45:26"],
    ["9mJhBzjugQg", "Mainframe modernization explained: COBOL and AI", "44:04"],
    ["3Wb6cA4CBIQ", "India's USD $200B AI hub & Claude builds C compiler", "49:40"],
    ["Lw5kD9xb9Ic", "Copilot usage reveals AI adoption patterns", "38:21"],
    ["C6PZwrsaii0", "Anthropic Claude Opus 4.6 vs OpenAI GPT-5.3-Codex: The AI \"big game”", "13:53"],
    ["9vW-zlWgGgo", "Codex launch & OpenClaw/Moltbook chaos: This week in AI agents", "24:57"],
    ["M-i1Uhzb1xA", "OpenClaw (Clawdbot): Open-source agents go mainstream", "45:28"],
    ["s3SHPOByMTY", "The new AI race: Enterprise innovation in 2026", "48:29"],
    ["ym8GvNQBqA0", "Claude Cowork analysis & Apple picks Gemini", "41:39"],
    ["5gRCyXOYF74", "CES 2026 AI highlights: NVIDIA Rubin & wild gadgets", "42:36"],
    ["ARXS-uk19h8", "AI year in review: Trends shaping 2026", "38:38"],
    ["oRRDAZtJLmk", "AI Code Generation: Wins, Fails and the Future", "35:19"],
    ["dJTwev1O-mE", "Disney's AI bet: USD 1B OpenAI content deal explained", "38:31"],
    ["nvAScf8YhzE", "GPT-5.2 code red & AWS Nova models drop", "41:42"],
    ["_lZgapJzFho", "AI model analysis: Mistral 3, DeepSeek-V3.2 & Claude Opus 4.5", "35:41"],
    ["SdNRWJ-oqjY", "AI agents in 2025: Why agentic commerce isn't ready for Black Friday yet", "41:31"],
    ["7T_TjH6P8CE", "Google’s Gemini 3: AI agents, reasoning and search mode", "46:43"],
    ["5sFJVAoafFI", "GPT-5.1 and Kimi K2: What ‘Thinking AI’ really means", "31:56"],
    ["9GhT1mp5Edk", "1X NEO humanoid robot enters the home", "36:29"],
    ["KF3jIUBecFo", "Anthropic’s TPU move and NVIDIA’s Starcloud", "47:39"],
    ["xawn4C43TWo", "ChatGPT Atlas, OpenAI’s new web browser", "44:48"],
    ["JQ0ZObgOoGQ", "OpenAI, Oracle & AMD shake up AI", "49:42"],
    ["lMrOvPloJ0o", "IBM partners with Anthropic, plus OpenAI drops AgentKit", "43:48"],
    ["LAXAmXHNGeM", "This week in AI models: Granite 4.0, Claude 4.5, Sora 2", "42:04"],
    ["h1YqbXQN5N8", "NVIDIA’s USD 100bn investment and Google's AP2", "52:42"],
    ["1PlyV-pf9_M", "Anthropic Economic Index, Virtual Agent Economies, AlterEgo and How People Use ChatGPT", "46:55"],
    ["SjoxdH9qOTE", "Why language models hallucinate, revisiting Amodei’s code prediction and AI in the job market", "42:25"],
    ["Qw8GOzs3Z0g", "Google Antitrust, Anthropic's $183B leap and are we in the AI winter?", "52:16"],
    ["zw0Ymg_DoEs", "Monster prompt, OpenAI’s business play, nano-banana and US Open experimentations", "44:05"],
    ["UKVSCFrWrpA", "Gen AI pilots fail, GPT-5's hidden prompt revealed, reasoning model flaws and Claude closing chats", "45:01"],
    ["HK17Bt5rUtc", "Perplexity’s bid for Chrome, Grok Imagine and GPT-5 check-in", "40:42"],
    ["A30mVgbG-OQ", "OpenAI dropped GPT-5, is AGI here?", "34:06"],
    ["Dtr0scHQVXc", "Gpt-oss, Genie 3, Personal Superintelligence and Claude pricing", "43:43"],
    ["EB3rWZPz0gk", "ChatGPT study mode, shift from UX to AX and Cost of a Data Breach Report 2025", "48:51"],
    ["6RYrUyxXsYU", "AI Action Plan, ChatGPT agents and DeepMind at IMO", "43:27"],
    ["hNvbeXus-pM", "Kimi K2, DeepSeek-R1 vibe check and Google’s data center investments", "47:52"],
    ["ieR3u8sUX-U", "Perplexity’s Comet browser, Cloudflare blocks AI scrapers and Wimbledon Match Chat", "52:01"],
    ["myIre7iONII", "Anthropic’s Project Vend, computer science education and AI prompts in papers", "49:53"],
    ["brrJRoqjVY4", "Your brain on ChatGPT, human-like AI for safer AVs, and AI-generated ads", "36:16"],
    ["SuDcg-lg5So", "Impact of AI on jobs, Scale AI fallout and chatbot conspiracies", "42:01"],
    ["Y5yiQDnTimU", "Apple’s WWDC, Meta & Scale AI, o3-pro and fault-tolerant quantum computing", "52:08"],
    ["tU9Jal1-E6c", "NY Tech Week, open source AI reports and Claude 4 behaviors", "44:42"],
    ["e_B91C2vILc", "Claude 4 system prompt, Jony Ive at OpenAI and Microsoft’s “agent factory”", "43:51"],
    ["Blq_pf6yd6U", "Claude 4: Everything you need to know", "27:38"],
    ["rNk3OuUj1UA", "Google I/O, NLWeb, llm-d and is Stack Overflow dead?", "42:02"],
    ["kjRHpuXGmH0", "Mistral Medium 3, OpenAI HealthBench and AI chips to Saudi Arabia", "36:42"],
    ["5M-VD9F1W7A", "IBM Think 2025, OpenAI Windsurf acquisition, reasoning models and hallucinations", "28:03"],
    ["yeutlpU13YM", "LlamaCon, Qwen3, DeepSeek-R2 rumors and JP Morgan’s open letter on AI", "39:46"],
    ["LnVkwuwL7LU", "OpenAI social network, Anthropic’s reasoning study and humanoid half-marathon", "38:04"],
    ["8e6StFBP0VM", "o3 and o4-mini, Google Gemini on-prem and NVIDIA’s U.S. chip manufacturing", "41:54"],
    ["90fUR1PQgt4", "AI on IBM z17, Meta's Llama 4 and Google Cloud Next 2025", "37:24"],
    ["x0DQfLQHT0Q", "OpenAI goes open, Anthropic on interpretability, Apple Intelligence updates and Amazon AI agents", "43:20"],
    ["CgqHN38l6Ko", "DeepSeek-V3-0324, Gemini Canvas and GPT-4o image generation", "41:40"],
    ["TsDdk7xHhMY", "NVIDIA GTC, Baidu reasoning models and Gemini AI image generation", "39:13"],
    ["Ddh3p185KhA", "Manus, vibe coding, scaling laws and Perplexity’s AI phone", "50:05"],
    ["iYRdhSEGpg4", "Quantum leap, Model Context Protocol, CoreWeave IPO and an AI voice companion", "45:23"],
    ["LQEhOObUhQg", "GPT-4.5: And the future of pre-training is...", "24:06"],
    ["561dyCTvGlQ", "Claude 3.7 Sonnet, BeeAI agents, Granite 3.2, and emergent misalignment", "39:42"],
    ["y4gm_4UFT28", "Deep Research, OpenAI inference chip, small VLMs, and AI agent job posting", "45:51"],
    ["KNNi-enb2B4", "Paris AI Summit, Altman's \"Three Observations,\" and Anthropic's Economic Index", "39:52"],
    ["qT8GgwQ2rT4", "OpenAI deep research, o3-mini, AI Action Summit, and Anthropic’s Constitutional Classifiers", "38:08"],
    ["jC0MGFDawWg", "DeepSeek facts vs hype, model distillation, and open source competition", "39:17"],
    ["86rz0mV3jZE", "DeepSeek-R1, Mistral IPO, FrontierMath controversy, and IDC code assistant report", "39:44"],
    ["NcV5GrG5VTA", "Anthropic valuation rumors, Microsoft CoreAI, NotebookLM upgrades, and AI agents in finance", "44:47"],
    ["KwGg5WhxuFY", "CES 2025, NVIDIA DIGITS, Apple Intelligence fails, and Sam Altman’s reflections", "35:32"],
    ["QzERUfTbKQw", "OpenAI o3, DeepSeek-V3, and the Brundage/Marcus AI bet", "39:17"],
    ["l8plyR8aqVQ", "2024 Rewind: Breakthroughs in AI models, agents, hardware and products", "1:01:35"],
    ["GnMKY4QLHDw", "Granite 3.1, NVIDIA Jetson, stealing AI models, and is pre-training over?", "40:28"],
    ["UVMndg9WX9g", "12 Days of OpenAI, NeurIPS, ARC Prize, and Llama 3.3 70B", "40:51"],
    ["ZEwJfi7xPxc", "Inside AWS re:Invent 2024, LLM Flowbreaking, and David Mayer", "37:50"],
    ["JSnwZmbTMXM", "AI in education: Safety, literacy, and predictions", "36:29"],
    ["Z-6d1gnSOAI", "“Near-infinite memory,” Microsoft Ignite, FrontierMath, and AlphaFold3", "43:07"],
    ["GP4UrwbzLT8", "Scaling AI, agent-led future, and race to AGI", "39:08"],
    ["V6vxTXrDCrA", "SearchGPT, from Naptime to Big Sleep, and GitHub Octoverse updates", "39:46"],
    ["HYHgJkWnPdQ", "The future of agents, AI energy consumption, Anthropic's computer use, and Google watermarking AI", "32:57"],
    ["5-xMSQZ9xx0", "Granite 3.0, NVIDIA’s Nemotron AI model, and Perplexity’s fundraising", "37:13"],
    ["BWKFzWUOBOg", "Machines of Loving Grace, Entropix, AI and elections, GSM8K", "41:11"],
    ["v9go9rttLO8", "AI in the Nobels, DGX B200 arrival, and Unstructured’s $40M funding round", "37:28"],
    ["GFQv0r9OGU0", "NotebookLM, OpenAI DevDay, and will AI prevent phishing attacks?", "39:23"],
    ["FnO6TD9LtPY", "Llama 3.2, AI Snake Oil, and gen AI for sustainability", "33:54"],
    ["KPsl7IK2_eo", "OpenAI o1 preview, Agentforce, AI in fantasy football, and machine unlearning", "48:01"],
    ["j9vTEhimRqk", "Apple Intelligence, Reflection 70B, open-source AI agents, and LLM research ideas", "38:35"],
    ["iSJenVM7KnQ", "NEO 1X Robot, OpenAI chips, The AI Scientist, and the future of prompt engineering", "38:12"],
    ["IKaj8gATzoY", "Cursor hype, Perplexity introduces ads, and AI at the US Open", "40:51"],
    ["emVMHYQVmdQ", "Agent Q, no AI in art, and AMD acquires ZT Systems", "47:26"],
    ["L1_cLO4d_zE", "Cost of a Data Breach 2024 and OpenAI's Project Strawberry", "23:03"],
    ["1tTXTDzaPyY", "OpenAI Structured Outputs, character.ai “acquisition,” and is it an AI bubble?", "32:09"],
    ["3mcLdfx6HTc", "SAM 2, friend.com, and will gen AI projects be abandoned?", "28:59"],
    ["bQzPaRYC9BE", "Meta's Llama 3.1, Mistral Large 2 and big interest in small models", "20:25"],
    ["Wlf6id2FH-Q", "Goldman Sachs Gen AI report, Claude 2.0 Engineer, and RIAA lawsuits", "31:15"],
    ["aMcYxjZMRuA", "AI at Wimbledon, ChatGPT for coding, and scaling with AI personas", "41:29"],
    ["rn1sjMFRzTQ", "AI Hardware: Training, Inference, Devices and Model Optimization", "38:25"],
    ["FjppatnFxsE", "Claude 3.5 Sonnet, BIRD-SQL, and the latest in AI Slop", "38:58"],
    ["G8lnNR1-rsw", "NVIDIA’s Nemotron-4 340B models, Safe Superintelligence Inc. and AI agents", "43:54"],
    ["_bCsW_Jrcts", "Apple's WWDC24 reactions and mechanistic interpretability", "39:48"],
    ["0sA6X6n3goc", "AI safety, RAG benchmarking and responsible AI at ACM FAccT Conference", "40:36"],
    ["VMmIdX9Zmuw", "Google’s AI Overviews, Golden Gate Claude, the \"whale computer\" and scaling laws", "44:31"],
    ["F0FHMakREDM", "Scarlett Johansson, FMTI and Think 2024", "38:51"],
    ["T6DGGHlkYa0", "GPT-4o, AI overviews and our multimodal future", "41:04"],
    ["K83tTEeGCBc", "The state of open source, InspectorRAGet, and what’s going on with Kolmogorov-Arnold Networks", "46:23"],
    ["hwNkFnR1U0I", "Mixture of Experts: Rabbit AI hiccups, GPT-2 chatbot, and OpenAI and the Financial Times", "41:35"],
  ],
  "PLOspHqNVtKAC0-KCayX4_nEfSjE8VhbZx": [
    ["Ac-BIziJPXQ", "L’Oréal and IBM: AI-Powered Beauty | Audio | Smart Talks with IBM", "26:37"],
    ["YqBYin9Bljw", "L'Oréal & IBM: Redefining Beauty Through AI Innovation | Highlights | Smart Talks with IBM", "4:15"],
    ["i7kEip4dhnY", "How AI Assistants Can Transform Education | Audio | Smart Talks with IBM", "27:22"],
    ["ROZRChEjHSg", "How AI Assistants Can Transform Education | Highlights | Smart Talks with IBM", "10:35"],
    ["BCc29YKiOGk", "How Infrastructure is Powering the Age of AI", "51:07"],
    ["goSJUSpsypE", "AI and the Productivity Paradox", "0:18"],
    ["utcYsBKL7e8", "How AI Can Accelerate Cybersecurity", "36:21"],
    ["VNWXOYf73tI", "Scaling AI with purpose", "34:35"],
    ["YIIbugJbgpE", "The Power of Granite in Business", "31:11"],
    ["2Yvwua9RHIM", "Education in the Age of AI", "42:00"],
    ["SkXgG6ksKTA", "How Open Source can Democratize AI", "34:11"],
    ["hwim1CYl0fI", "An AI advantage for the US Open", "32:23"],
    ["iaisOHeJLC4", "AI and the Productivity Paradox", "39:07"],
    ["IQd-DIxK8HA", "AI in healthcare: how generative AI is expanding fertility treatment", "34:15"],
    ["MaIFF5h2_UM", "Salesforce & IBM: revolutionizing experiences with generative AI", "39:47"],
    ["Si5rhjifbZs", "Generative AI: Its Rise and Potential for Society", "52:03"],
    ["MluoD8Z1ARQ", "Responsible AI: why businesses need reliable AI governance", "26:59"],
    ["THEQbJIAxvE", "Hugging Face and watsonx: why open source is the future of AI in business", "30:43"],
    ["kLBdpNsXh1A", "Transformations in AI: why foundation models are the future", "39:05"],
    ["hzAUCHh90Fg", "AI for business: multiplying the impact of AI", "32:23"],
  ],
  "PLOspHqNVtKABGIbaWP1xYQHbwuXjZwqpH": [
    ["dHn0qzSDMO0", "Can you trust your chatbot? Inside three AI-powered cyberattacks", "34:54"],
    ["GvPJY72WhoY", "Are AI labs ignoring cybersecurity experts?", "37:20"],
    ["t8Y-eqZ5_-0", "The vulnpocalypse might not be so bad after all", "33:58"],
    ["6AuYLbHqirk", "Why won’t AI agents just follow the rules?", "35:29"],
    ["-0p68wKEitE", "Why OpenAI is calling for a ‘cyber defense surge.’ Plus: Find Evil! winners and TeamPCP losers", "29:09"],
    ["nWgvobB4hcw", "Who’s afraid of an open-weight model? GLM, context bombing and post-Black Hat attacks", "26:43"],
    ["3zhveTN1VzE", "What should security leaders do with AI? They don’t know.", "29:15"],
    ["auS34nm9VAc", "The OWASP LLM Top 10 has a few surprises for you", "29:05"],
    ["A9nnvw2wqmE", "Oh look. Anthropic’s AI models also broke containment.", "34:31"],
    ["lx41qvj80Jo", "The Cost of a Data Breach 2026, and what we can learn from the Hugging Face hack", "32:08"],
    ["g4CNcUAqM4Q", "GPT-Red: Can AI red teams stop prompt injections?", "31:30"],
    ["qXGJ7pi-XOo", "GLM-5.2: The real security risk? Plus: Vibe hunting, the end of CVSS and updates on Lightwell", "35:06"],
    ["HQDT_1OXUuU", "Fable 5, GPT-5.6 and the high stakes of AI safeguards. Agentic ransomware, ClickFix reigns supreme", "42:02"],
    ["RYUR9BdDgyI", "The new post-quantum cryptography executive order. Plus: What is Q-Day, really?", "44:12"],
    ["10XtOi4Lbes", "Have we finally solved social engineering? Plus: World Cup fraud, AI IDs and an IBM/OpenAI collab", "39:11"],
    ["ATIwByZ4nUA", "AI agents can manage your passwords. Should we let them? Plus: The biggest Patch Tuesday ever.", "30:22"],
    ["JHDsM8ER7tk", "Can you social engineer an AI? Plus: AI worms and the nonhuman identity problem", "32:49"],
    ["aa6k-JrZTYI", "Project Lightwell brings open source security into the AI era", "35:16"],
    ["ftUlJzuzdU4", "First findings from Project Glasswing", "33:10"],
    ["u2MFautDjuM", "OpenAI’s Daybreak and Mistral’s Mythos competitor", "30:03"],
    ["oRZK7fcBQIg", "LLMjacking: How hackers steal your AI API keys and stick you with the bill", "31:27"],
    ["EJg67cLfLYo", "Claude Security’s public beta, OpenAI’s five-point plan and cybersecurity’s Y2K moment", "30:04"],
    ["PJGIWDW_W2A", "Is open source safe? Featuring Mixture of Experts", "25:23"],
    ["TYpg5oxSQ6Y", "Should you let OpenClaw pen test your system? Plus: Cybersecurity for ephemeral software", "36:13"],
    ["xbvI5G-8q4o", "GPT-5.4-Cyber: What you need to know", "11:42"],
    ["x_fBn7lto4Q", "Claude Mythos: Marketing hype or the end of cybersecurity?", "29:33"],
    ["qtFtECYOzZE", "The Claude Code source code leak: Takeaways for cybersecurity pros", "41:31"],
    ["0nPkGvNS0n8", "RSA recap, the LiteLLM breach, and the quest to fix AI agent security", "48:44"],
    ["HycfWDXMr5Q", "Promptware, cloud security trends for 2026, and what the Xbox One hack means for cybersecurity", "40:49"],
    ["MV4VbPmehOQ", "Perplexity Comet, agentic blabbering, and the shift-left failure", "36:54"],
    ["4Htg_J4DcgU", "The conference that changed our minds about AI", "38:25"],
    ["lc5bp6wVVmQ", "Is your robot vacuum safe? Here’s why it matters.", "53:17"],
    ["vcS02Vl6IU0", "Exploits of public-facing apps are surging. Why?", "47:16"],
    ["gCwYOTmZOVc", "Romance scams: How they work, how they win and what we do about it", "37:29"],
    ["g9LO9M1ZLIk", "OpenClaw and Claude Opus 4.6: Where is AI agent security headed?", "47:49"],
    ["F0QCrxwwSg0", "What cybersecurity pros need to know about OpenClaw and Moltbook", "45:23"],
    ["tF8nJM4qOLE", "The newest AI malware vs. 40 years of hacker culture", "39:36"],
    ["l0XwNeGGPnQ", "Most cybersecurity training doesn’t work. Can we change that?", "32:17"],
    ["AIh04-APeHo", "Ransomware whack-a-mole, AI agents as insider threats and how to hack a humanoid robot", "41:18"],
    ["50e3h0Q7RTE", "A new take on bug bounties, AI red teams and our New Year’s resolutions", "40:37"],
    ["gwL3iivVkiA", "Cybersecurity’s Year in Review: ClickFix Attacks, Vibecoding Vulnerabilities & Shadow Agents", "57:18"],
    ["8jWAQiSqDVU", "AI browser bans and the top software flaws of 2025", "51:43"],
    ["LWGdsBMPcnY", "React2Shell makes waves, WormGPT falls flat and the latest threat to your Gmail account", "50:12"],
    ["o3caaeeCPXg", "Your house might be a botnet, your devs are leaking secrets and poems are breaking your AI guardrail", "42:59"],
    ["x1yRb5_PVro", "The dark web job market thrives, AI fraud rings rise and it’s holiday scam season.", "40:01"],
    ["LNVDrrKbfzg", "Anthropic stops AI spies, the new OWASP Top 10 and the rise of small-time ransomware", "40:14"],
    ["N_wGf6PAP5U", "AI slop in cybersecurity, OT security fails and lessons from the Louvre heist", "41:38"],
    ["iaZS1jer8MY", "Android malware that acts like a person and AI agents that act like malware", "41:31"],
    ["zc8qBG99GWk", "Is ChatGPT Atlas safe? Plus: invisible worms, ghost networks and the AWS outage", "44:08"],
    ["sVxSCcwlxus", "RIP Windows 10, automated code repair and battling the payroll pirates", "46:19"],
    ["mDpUZD1ogEE", "How to scam an AI agent, DDoS attack trends and busting cybersecurity myths", "50:07"],
    ["7y4cYOdf0Y4", "The AI vulnerability apocalypse, a new strain of Petya and dumb cybersecurity rules", "42:48"],
    ["dAS4zgMiSuQ", "AI ransomware, hiring fraud and the end of Scattered Lapsus$ Hunters", "46:12"],
    ["u-ZRZX2VZh4", "Vibe hacking, HexStrike AI and the latest scheme from Scattered Lapsus$ Hunters", "38:14"],
  ],
  "PLOspHqNVtKAC-_ZAGresP-i0okHe5FjcJ": [
    ["20QUNgFIrK0", "Software as a Service (SaaS) Explained in 5 mins", "5:23"],
    ["KaCyfQ7luVY", "Public Cloud Explained", "9:08"],
    ["3kGFBBy3Lyg", "Hybrid Cloud Explained", "6:36"],
    ["XRdmfo4M_YA", "IaaS Explained", "8:07"],
    ["QAbqJzd0PEE", "PaaS Explained", "6:38"],
    ["EOIja7yFScs", "What is FaaS (Functions as a Service)?", "10:52"],
    ["NbkPRn1mqlU", "What is a Virtual Private Cloud?", "4:51"],
    ["CdBtNQZH8a4", "What are Microservices?", "6:38"],
    ["kBF6Bvth0zw", "Container Orchestration Explained", "9:00"],
    ["0qotVMX-J5s", "Containerization Explained", "8:09"],
    ["FZR0rG3HKIk", "Virtualization Explained", "5:20"],
    ["cjXI-yxqGTI", "Containers vs VMs: What's the difference?", "8:08"],
    ["aSrqRSk43lY", "Kubernetes Explained", "10:59"],
    ["CAQ_a2-9UOI", "Observability vs. APM vs. Monitoring", "9:41"],
    ["fp9_ubiKqFU", "What is Cloud Native?", "4:37"],
    ["UbtB4sMaaNM", "What is DevOps?", "5:59"],
    ["yWByEVB0VJE", "What is Cloud Migration?", "4:47"],
    ["jI8IKpjiCSM", "What is Cloud Security?", "10:17"],
    ["9dzb6eNhqOE", "Hybrid Multicloud Use Cases", "6:44"],
    ["KIjP0dDHu5w", "Virtual Private Clouds on IBM Cloud", "4:05"],
    ["78wvDIK5Hys", "IBM Cloud Paks Explained", "7:28"],
    ["AjtdZ3gFRjU", "What is Multicloud? How Do You Manage It?", "5:59"],
    ["RJ3UQSxwGFY", "Application Modernization: Three Transformations at Once", "8:09"],
    ["aj9CDZm0Glc", "What is Kafka?", "9:17"],
    ["eJHZ8sMjsug", "What is Distributed Cloud?", "9:06"],
    ["OmphHSaO1sE", "What is etcd?", "6:18"],
    ["TiEwRiX6kGo", "What is a Cloud Shell?", "9:11"],
    ["fh3VaXLzH5Y", "What is API Management?", "10:02"],
    ["lsMQRaeKNDk", "What is a REST API?", "9:12"],
    ["wpISo9TNjfU", "Git vs. GitHub: What's the difference?", "10:06"],
    ["b_euX_M82uI", "Container Security Explained", "6:51"],
    ["pRS9LRBgjYg", "REST API and OpenAPI: It’s Not an Either/Or Question", "9:17"],
    ["fHO1X93e4WA", "What is Ansible?", "11:06"],
    ["pMHxLBJ6_UA", "What is Confidential Computing?", "8:46"],
    ["vxJobGtqKVM", "What is Serverless?", "6:42"],
    ["NPFbYpb0I7w", "Kubernetes Ingress in 5 mins", "5:41"],
    ["AJa2B-twtG4", "What are Feature Flags?", "6:40"],
    ["BgrQ16r84pM", "How does Kubernetes create a Pod?", "9:55"],
    ["6EUSwMX7D48", "Choosing a CSP for your SAP workloads", "6:26"],
    ["sUoeVhbp4cQ", "What is Hybrid Cloud?", "9:45"],
    ["fYcdKVBo1VY", "How to deploy SAP in the cloud", "7:29"],
    ["5bAhqB4WXkA", "Modernize apps with IBM Garage Methodology", "9:54"],
    ["ztIIcXNzMN4", "What is Site Reliability Engineering (SRE)?", "8:12"],
    ["KCzNd3StIoU", "DevOps vs. SRE: What's the difference?", "8:23"],
    ["07EHsPuKXc0", "Disaster Recovery vs. Backup: What's the difference?", "9:32"],
    ["o2HJCGcYwoU", "What is Event-Driven Architecture (EDA)?", "12:10"],
    ["3xH1SAWWdl0", "Bare Metal with a Hypervisor vs. Dedicated Host: What's the difference?", "5:21"],
    ["LMAEbB2a50M", "What is a Hypervisor?", "6:32"],
    ["rx4Uh3jv1cA", "Ansible vs. Terraform: What's the difference?", "9:32"],
    ["zL_A6wAvxGU", "What is a Dedicated Host?", "3:21"],
    ["k4tK2ttdSDg", "What is a Data Warehouse?", "8:21"],
    ["42fwh_1KP_o", "What is a Virtual Server?", "7:07"],
    ["Da1hUqzoiAo", "What is Enterprise Resource Planning (ERP) Software?", "10:24"],
    ["o9-ObGgfpEk", "What is a Chatbot?", "9:42"],
    ["9gGnTQTYNaE", "What is Machine Learning?", "8:23"],
    ["VOLeKvNz-Zo", "What is MongoDB?", "5:39"],
    ["muqiHwa8UvQ", "What is Redis?", "4:45"],
    ["7t3lTYEd_PM", "What is Root Cause Analysis (RCA)?", "8:32"],
    ["tzBgFog6NmY", "What is a LAMP Stack?", "7:55"],
    ["usqwC2MIho8", "What is the MEAN Stack?", "6:47"],
    ["ZP0NmfyfsoM", "What is Elasticsearch?", "9:53"],
    ["t_p4ZyAYyaY", "What is Django?", "7:44"],
    ["uC2JRAqYNeo", "What is Hybrid Cloud in 2022?", "6:44"],
    ["DP7TSgc6glc", "The MEAN Stack Explained", "6:40"],
    ["EKi8CN94dx4", "LAMP Stack Explained in 3 Minutes", "2:55"],
    ["slEPd5qb98U", "Optimizing Data Centers: Energy Efficiency & Cloud Repatriation Strategies", "6:02"],
  ],
  "PLOspHqNVtKABAVX4azqPIu6UfsPzSu2YN": [
    ["2vMEQ5zs1ko", "Kubernetes vs. Docker: It's Not an Either/Or Question", "8:04"],
    ["0qotVMX-J5s", "Containerization Explained", "8:09"],
    ["aSrqRSk43lY", "Kubernetes Explained", "10:59"],
    ["fy8SHvNZGeE", "What is Helm?", "9:06"],
    ["cTPFwXsM2po", "Kubernetes and OpenShift: What's the Difference?", "7:27"],
    ["NPFbYpb0I7w", "Kubernetes Ingress in 5 mins", "5:41"],
    ["kBF6Bvth0zw", "Container Orchestration Explained", "9:00"],
    ["ZsOR8RkAOwI", "Kubernetes vs. OpenShift", "9:20"],
    ["i9V4oCa5f9I", "Kubernetes Operators Explained", "9:35"],
    ["1iyFq2VaL5Y", "What is Istio?", "3:44"],
    ["Xx588nbshlM", "Podman vs. Docker", "6:33"],
    ["BgrQ16r84pM", "How does Kubernetes create a Pod?", "9:55"],
    ["69OfdJ5BIzs", "What is Knative?", "7:59"],
    ["Sulw5ndbE88", "Kubernetes Deployments: Get Started Fast", "3:55"],
    ["6h-UCGJ4-BA", "Using IBM CloudLabs for Hands-on Kubernetes Training on IBM Cloud", "1:39"],
    ["1Br4m0_8YDQ", "Advantages of Managed Kubernetes", "3:15"],
    ["j64WdNBqoWk", "No code change approach to confidential computing", "6:36"],
    ["F0hNDkAA1sM", "Flexibly driving high scale apps in production with Kubernetes", "1:59"],
  ],
  "PLOspHqNVtKACSagAEeIY20NMVLNeQ1ZJx": [
    ["fp9_ubiKqFU", "What is Cloud Native?", "4:37"],
    ["CdBtNQZH8a4", "What are Microservices?", "6:38"],
    ["zWw2wuiKd5o", "What is Infrastructure as Code?", "8:51"],
    ["6zDrLvpfCK4", "Istio Service Mesh Explained", "5:13"],
    ["oUpqXxmr6oU", "Cloud Foundry Explained", "10:31"],
    ["69OfdJ5BIzs", "What is Knative?", "7:59"],
    ["cjXI-yxqGTI", "Containers vs VMs: What's the difference?", "8:08"],
    ["fh3VaXLzH5Y", "What is API Management?", "10:02"],
    ["kG-fLp9BTRo", "API vs. SDK: What's the difference?", "9:21"],
    ["wpISo9TNjfU", "Git vs. GitHub: What's the difference?", "10:06"],
    ["vxJobGtqKVM", "What is Serverless?", "6:42"],
    ["sKfep-UmZeM", "Architecting a Cloud Native API Solution", "10:29"],
    ["o2HJCGcYwoU", "What is Event-Driven Architecture (EDA)?", "12:10"],
  ],
  "PLOspHqNVtKADX-InvL3aRFYuOYvi-Qmep": [
    ["aSrqRSk43lY", "Kubernetes Explained", "10:59"],
    ["i9V4oCa5f9I", "Kubernetes Operators Explained", "9:35"],
    ["2vMEQ5zs1ko", "Kubernetes vs. Docker: It's Not an Either/Or Question", "8:04"],
    ["UmIomb8aMkA", "Kubernetes Operators Explained", "6:48"],
    ["ZsOR8RkAOwI", "Kubernetes vs. OpenShift", "9:20"],
  ],
  "PLOspHqNVtKAAm1dmyiR9WMmw1UBoOwZVj": [
    ["UbtB4sMaaNM", "What is DevOps?", "5:59"],
    ["7aSe1HQ2lXo", "Tekton vs. Jenkins: What's the difference?", "15:59"],
    ["KCzNd3StIoU", "DevOps vs. SRE: What's the difference?", "8:23"],
    ["ztIIcXNzMN4", "What is Site Reliability Engineering (SRE)?", "8:12"],
    ["zWw2wuiKd5o", "What is Infrastructure as Code?", "8:51"],
    ["1er2cjUq1UI", "What is Continuous Integration?", "6:21"],
    ["J73MELGF6u0", "What is DevSecOps?", "6:55"],
    ["iITmoI0s1DQ", "What is Continuous Improvement?", "4:59"],
    ["2TTU5BB-k9U", "What is Continuous Delivery?", "5:51"],
    ["LNLKZ4Rvk8w", "Continuous Deployment vs. Continuous Delivery", "5:35"],
    ["RYQbmjLgubM", "What is Continuous Testing?", "7:18"],
    ["Yto8nUeki-s", "What is Value Stream Management?", "9:20"],
    ["RJ3UQSxwGFY", "Application Modernization: Three Transformations at Once", "8:09"],
    ["TWxKD9dLpmk", "What is Tekton?", "6:49"],
    ["HmxkYNv1ksg", "Terraform Explained", "8:44"],
    ["rx4Uh3jv1cA", "Ansible vs. Terraform: What's the difference?", "9:32"],
    ["tQtni2st3xo", "GitOps on Multicloud Explained", "5:27"],
    ["-U9E1PhrM3o", "SRE Golden Signals Explained", "5:43"],
  ],
  "PLOspHqNVtKAA75RfVxm-CLdARe0VpBwbx": [
    ["CAQ_a2-9UOI", "Observability vs. APM vs. Monitoring", "9:41"],
    ["dXohgVATzDc", "APM vs Observability", "4:27"],
    ["oQDpBwKrx3s", "Application Health Through Observability", "4:32"],
  ],
  "PLOspHqNVtKAAihZ-Zrs1Gk7BZjqaa1pi2": [
    ["Y1vpWDusoSs", "FinOps for Trustworthy Cloud Automation", "6:53"],
  ],
  "PLOspHqNVtKAAAq9pHWlEiRUVcYMCcu4X0": [
    ["hWRRdICvMNs", "What is an API Gateway?", "10:19"],
    ["DBZTNzrZC3E", "Why API Management?", "7:59"],
    ["lsMQRaeKNDk", "What is a REST API?", "9:12"],
    ["fh3VaXLzH5Y", "What is API Management?", "10:02"],
    ["pRS9LRBgjYg", "REST API and OpenAPI: It’s Not an Either/Or Question", "9:17"],
    ["kG-fLp9BTRo", "API vs. SDK: What's the difference?", "9:21"],
    ["sKfep-UmZeM", "Architecting a Cloud Native API Solution", "10:29"],
    ["hFRpTVZpz8M", "Top API Use Cases", "18:19"],
    ["qGFRbOq4fmQ", "What's the Difference Between APIs, Services and Microservices?", "12:18"],
    ["h3SiItf_0Vw", "Take Your Next Step in the API Economy", "1:25"],
    ["OAdOa31EH4o", "Scaling an Online Store Without an API Gateway", "8:08"],
    ["PTfZcN20fro", "GraphQL vs REST: Which is Better for APIs?", "7:31"],
  ],
  "PLOspHqNVtKACfjqfEwR3iKz1gJILKj5Tn": [
    ["aXMPqfZt1gk", "Fight Insider Threats with AI-infused SIEM", "7:16"],
    ["mqzP7gJDM2s", "What is Malware? Let's Hear the Hacker's Viewpoint", "5:31"],
    ["8ZlHOZlNIKk", "EDR vs. EPP vs. NGAV", "3:53"],
    ["PsT2joRNvpI", "IBM Security X-Force Threat Intelligence Index Trends 2023", "4:44"],
    ["55GaIolVVqI", "What is Endpoint Detection and Response (EDR)?", "5:34"],
    ["NqKid53v5x8", "What is ASM (Attack Surface Management)?", "5:15"],
    ["0ctat6RBrFo", "Tech Talk: What is Public Key Infrastructure (PKI)?", "9:22"],
    ["3MsxAwEshfk", "SIEM or XDR", "4:56"],
    ["bOPhZiW0-Rs", "What is a Risk Analytics Center and How Can it Prevent a Security Breach?", "8:00"],
    ["6P_BFdTIoh4", "Using Tanium Comply in the IBM Cloud Security and Compliance Center", "5:26"],
    ["H13zWZrstCk", "Intro to IBM Cloud Security and Compliance Center", "5:22"],
    ["FMMWSLIcaME", "Cybersecurity and Zero Trust", "17:59"],
    ["V4wmb5KVmKM", "What is CSPM (Cloud Security Posture Management)?", "4:54"],
    ["yn6CPQ9RioA", "Zero Trust Explained in 4 mins", "3:43"],
    ["imNfrtvYYbw", "What is Ransomware?", "12:48"],
    ["j64WdNBqoWk", "No code change approach to confidential computing", "6:36"],
    ["Bp00VqBH420", "Data Security and Protection with Zero Trust", "2:51"],
    ["1cA1qOLaFGQ", "Quantum Computing impact on Cryptography", "2:10"],
    ["rH9-m7AhJhk", "Artificial Intelligence for smarter Cybersecurity", "3:14"],
    ["xtNpPI9dHio", "Intro to IBM Cloud Data Shield", "3:29"],
    ["o28kWyxoiV8", "Intro to IBM Cloud Hyper Protect Services", "5:52"],
    ["pMHxLBJ6_UA", "What is Confidential Computing?", "8:46"],
    ["b_euX_M82uI", "Container Security Explained", "6:51"],
    ["iETENR5MEB8", "What is Secrets Management?", "9:11"],
    ["AT6hhvanus8", "Data protection and compliance with IBM Cloud", "3:32"],
    ["jI8IKpjiCSM", "What is Cloud Security?", "10:17"],
    ["J73MELGF6u0", "What is DevSecOps?", "6:55"],
    ["cEOUeItHDdo", "What is edge computing?", "10:40"],
    ["z503nLsfe5s", "What is a DDoS Attack?", "3:52"],
    ["QphJEO9ZX6s", "Blockchain Explained", "10:23"],
    ["2llWuivdS7w", "NAT and Firewall Explained", "9:24"],
    ["bvVgP4tw_Hc", "Observability Explained with LogDNA", "8:16"],
  ],
  "PLOspHqNVtKAA_5N3pI49wkH4WsTkeZ_iQ": [
    ["sCR3SAVdyCc", "What is a Load Balancer?", "8:22"],
    ["nyH0nYhMW9M", "What is DNS (Domain Name System)?", "7:25"],
    ["kZTF7wIykk4", "Data Transfer Explained", "4:32"],
    ["u0TgGIn2LIM", "Virtual Networking Explained", "8:25"],
    ["2llWuivdS7w", "NAT and Firewall Explained", "9:24"],
    ["Bsq5cKkS33I", "What is a Content Delivery Network (CDN)?", "4:36"],
    ["s_92RqaqcfE", "vRAN vs. RAN: What's the difference?", "5:56"],
    ["5KKoniXgHy0", "What is an MZR? (Multi-Zone Region)", "9:33"],
  ],
  "PLOspHqNVtKAAXDobTc9kBWwnfgzNV2k_a": [
    ["Q5aTUc7c4jg", "SQL vs. NoSQL: What's the difference?", "6:06"],
    ["qfiOVB3yMHQ", "What is DBaaS? Should you use it?", "7:41"],
    ["OW5OgsLpDCQ", "What is ETL (Extract, Transform, Load)?", "4:52"],
    ["aOE90VAVOcU", "CouchDB Explained", "2:57"],
    ["muqiHwa8UvQ", "What is Redis?", "4:45"],
    ["ZfTOQJlLsAs", "What is Object Storage?", "10:28"],
    ["5EqAXnNm0FE", "Block Storage vs. File Storage", "4:04"],
    ["LxcH6z8TFpI", "What is a Data Lake?", "5:18"],
    ["OmphHSaO1sE", "What is etcd?", "6:18"],
    ["IPkQpBdde5Y", "Data Lakes in the Cloud", "14:40"],
    ["xtVnAhgtSI0", "Veeam Backup", "3:38"],
    ["bvVgP4tw_Hc", "Observability Explained with LogDNA", "8:16"],
    ["oQJWC74iALw", "IBM Cloud Object Storage: Built for business", "4:11"],
    ["OqjJjpjDRLc", "What is a Relational Database?", "7:54"],
    ["zPNCp9AV-vA", "What is VMware?", "6:46"],
    ["ZP0NmfyfsoM", "What is Elasticsearch?", "9:53"],
    ["PmxWTTpXNLI", "Block vs. File Storage", "10:52"],
    ["O-XBhVv2pgE", "What is Cloud Storage?", "8:55"],
    ["k4tK2ttdSDg", "What is a Data Warehouse?", "8:21"],
    ["07EHsPuKXc0", "Disaster Recovery vs. Backup: What's the difference?", "9:32"],
    ["VOLeKvNz-Zo", "What is MongoDB?", "5:39"],
    ["UO-yT7Ugnls", "What is MySQL?", "9:31"],
    ["w49ZtExnOsk", "Netezza as a Fully Managed Service on Cloud", "4:20"],
    ["0Zzn4eVbqfk", "Data Fabric Explained", "13:34"],
    ["FQGA6UTS3-k", "Netezza Performance Server on Cloud Pak for Data", "3:56"],
    ["Enu-EH7RHHM", "Data Lakehouses Explained", "8:51"],
  ],
  "PLOspHqNVtKABPTyvxoNW0e4XSgCNdZ40F": [
    ["sUoeVhbp4cQ", "What is Hybrid Cloud?", "9:45"],
    ["3kGFBBy3Lyg", "Hybrid Cloud Explained", "6:36"],
    ["h_WE-ZFDZJQ", "Hybrid Cloud Architecture: Introduction", "3:56"],
    ["Fp2In_la9DE", "Hybrid Cloud Architecture Part 1: Connectivity", "13:19"],
    ["iZR0TJPmj_U", "Hybrid Cloud Architecture Part 2: Modernize", "11:23"],
    ["_bjDY9omL9I", "Hybrid Cloud Architecture Part 3: Security", "13:14"],
    ["RJ3UQSxwGFY", "Application Modernization: Three Transformations at Once", "8:09"],
    ["uC2JRAqYNeo", "What is Hybrid Cloud in 2022?", "6:44"],
  ],
  "PLOspHqNVtKACWzKwzaPCPTiByXhyRY8NU": [
    ["vxJobGtqKVM", "What is Serverless?", "6:42"],
    ["QAbqJzd0PEE", "PaaS Explained", "6:38"],
    ["XRdmfo4M_YA", "IaaS Explained", "8:07"],
    ["FzERTm_j2wE", "Cloud Native DevOps Explained", "11:11"],
    ["nOtxRNQAKXA", "Tech Talk: ArgoCD + Tekton = Better GitOps", "5:59"],
    ["BYTgP6GmwcQ", "GitOps and Cloud Adoption: You Need Both", "5:01"],
  ],
  "PLOspHqNVtKABcMvsegAjlnKYMMV5KsSml": [
    ["AjtdZ3gFRjU", "What is Multicloud? How Do You Manage It?", "5:59"],
    ["BcV5wHyMhfs", "Multicloud Security Explained", "4:19"],
    ["aH4nz3mQIng", "Multicloud management: Drive security and save your brand", "5:52"],
    ["CDtjlshp1KI", "Multicloud vs. hybrid cloud and how to manage it all", "9:40"],
    ["kI62_Xw2Qgg", "Deploy apps and run anywhere with IBM Cloud Satellite", "6:27"],
    ["4H4dAtrl4p0", "IBM Cloud Satellite Use Cases", "5:13"],
    ["rOp7aGyavnk", "Securely manage your cloud secrets with IBM Cloud Secrets Manager", "2:53"],
    ["8WNjwlN5gMk", "Setting up an On-Premises Satellite Location with Mini PCs", "5:05"],
    ["KbMkPgaH-y0", "IBM Cloud Satellite Overview", "2:16"],
  ],
  "PLOspHqNVtKACLF9lk3edNG43LfUPcWioZ": [
    ["cEOUeItHDdo", "What is edge computing?", "10:40"],
    ["-ozeyxYu1ek", "The Future of Edge Computing", "5:47"],
    ["AF5ZkcnptMs", "Why Edge Computing?", "2:37"],
    ["c3NKe8-3qB8", "The Future of Edge Computing: Communications Service Provider / Telco", "3:14"],
    ["BHCUG6Wsr5Q", "The Future of Edge Computing: Banking & Financial Services", "3:28"],
    ["Sae1YgvhAmM", "The Future of Edge Computing: Retail", "3:40"],
    ["Do7gsyXWj4E", "What is Multi-access Edge Computing (MEC)?", "5:29"],
    ["5InwlTrl4aY", "IBM Edge Computing helps NASA analyze DNA in Space", "4:36"],
  ],
  "PLOspHqNVtKABpPMnwkx27tEO2KOBvHLu6": [
    ["GE3JOFwTWVM", "What is Time Series Analysis?", "7:29"],
    ["7rs0i-9nOjo", "What is Data Mining?", "6:53"],
    ["0Zzn4eVbqfk", "Data Fabric Explained", "13:34"],
    ["CiSaY2xl9V4", "Ten Everyday Machine Learning Use Cases", "7:07"],
    ["HIusawrGBN4", "What is Synthetic Data? No, It's Not \"Fake\" Data", "6:49"],
    ["jfg9wBJBtKk", "What is Data Observability?", "12:02"],
    ["0RT2Q0qwXSA", "Overfitting, Underfitting, and Bad Data Are Ruining Your Predictive Models", "6:49"],
    ["-n3OD-ml_k0", "What is a Data Contract?", "3:04"],
    ["aBIxpJ1_EyY", "What Is Real-Time Data Streaming? AI & Machine Learning Applications", "9:24"],
    ["hPJXcu5ggMI", "What is Data Integration? Unlocking AI with ETL, Streaming & Observability", "7:12"],
  ],
  "PLOspHqNVtKAD74tcRKW9FhETyKSaKxl3J": [
    ["hRulZhTtUTg", "What is a Database?", "7:36"],
    ["k4tK2ttdSDg", "What is a Data Warehouse?", "8:21"],
    ["Enu-EH7RHHM", "Data Lakehouses Explained", "8:51"],
    ["E9AgJnsEvG4", "Relational vs. Non-Relational Databases", "8:12"],
    ["qfiOVB3yMHQ", "What is DBaaS? Should you use it?", "7:41"],
    ["N8TFwV4Q_w0", "Why a Data Lakehouse Architecture", "8:02"],
  ],
  "PLFV4g2rfT2rs": [
    ["uPsUjKLHLAg", "Data Governance Explained in 5 Minutes", "5:22"],
    ["4QXtObc61Lw", "Security & AI Governance: Reducing Risks in AI Systems", "15:10"],
    ["Q020C-Jw0o8", "The Importance of AI Governance", "9:11"],
    ["yh-3WU1FKrk", "What is Responsible AI? A Guide to AI Governance", "6:06"],
    ["5hK7pQsvpy0", "Building an AI Agent Governance Framework: 5 Essential Pillars", "10:04"],
    ["LyfG7SGRiZA", "Protecting Data in AI: Strategies for Security & Governance", "15:20"],
    ["446x7GqXdaA", "AI Agents Best Practices: Monitoring, Governance, & Optimization", "9:11"],
    ["Ixt-4T6oxk4", "Data Governance vs. Model Governance: Building a Strong Foundation for AI", "5:46"],
    ["kLaBaJyBe4I", "Generative AI Under Control: Real-World Governance Examples", "5:35"],
  ],
  "PLAZfI25B5sr0": [
    ["aj9CDZm0Glc", "What is Kafka?", "9:17"],
    ["6kEGUCrBEU0", "What Are Data Pipelines?", "8:29"],
    ["o2HJCGcYwoU", "What is Event-Driven Architecture (EDA)?", "12:10"],
    ["KIv2Na2-u24", "ETL vs ELT: Powering Data Pipelines for AI & Analytics", "6:51"],
    ["aBIxpJ1_EyY", "What Is Real-Time Data Streaming? AI & Machine Learning Applications", "9:24"],
    ["p8DA_ca86-c", "Event-Driven Business Capabilities: Automation, Discovery, and Processing", "3:20"],
  ],
  "PLOspHqNVtKABIVwvKy4xY0lz0FUPnH1JD": [
    ["0Zzn4eVbqfk", "Data Fabric Explained", "13:34"],
    ["24Ki4Ck4Y2E", "Data Governance Explained", "7:47"],
    ["jfg9wBJBtKk", "What is Data Observability?", "12:02"],
  ],
  "PLOspHqNVtKADA_xaKgpekj_bgqsC58VXm": [
    ["LxcH6z8TFpI", "What is a Data Lake?", "5:18"],
    ["IPkQpBdde5Y", "Data Lakes in the Cloud", "14:40"],
    ["FQGA6UTS3-k", "Netezza Performance Server on Cloud Pak for Data", "3:56"],
    ["w49ZtExnOsk", "Netezza as a Fully Managed Service on Cloud", "4:20"],
    ["Enu-EH7RHHM", "Data Lakehouses Explained", "8:51"],
  ],
  "PLOspHqNVtKABPJWHc_2VOHGtjwaxnw5fE": [
    ["LxcH6z8TFpI", "What is a Data Lake?", "5:18"],
    ["k4tK2ttdSDg", "What is a Data Warehouse?", "8:21"],
    ["07EHsPuKXc0", "Disaster Recovery vs. Backup: What's the difference?", "9:32"],
    ["VOLeKvNz-Zo", "What is MongoDB?", "5:39"],
    ["muqiHwa8UvQ", "What is Redis?", "4:45"],
    ["aOE90VAVOcU", "CouchDB Explained", "2:57"],
    ["ZHP2jQ6bFZU", "IBM Cloud Object Storage - flexible storage built for rapid change", "2:18"],
    ["IPkQpBdde5Y", "Data Lakes in the Cloud", "14:40"],
    ["xtVnAhgtSI0", "Veeam Backup", "3:38"],
    ["yG1ng3vEVPU", "What is SaaS Backup?", "5:32"],
    ["lCuJnhZaTv8", "What is Computational Storage?", "10:00"],
    ["uVJ98XaUVV4", "SaaS Backup Capabilities", "6:30"],
  ],
  "PLOspHqNVtKADRD_mso6us7QpiSJ9AlY5r": [
    ["jRMbbRdju7Q", "When Should AI Systems Use Super Agents?", "11:26"],
    ["SbrEk_tXZaE", "Why AI Agents Break Zero Trust at the Last Mile", "13:15"],
    ["ZrHKwxasXS4", "The Rise of Crypto Agility: How to Secure Systems for the Quantum Era", "12:40"],
    ["ZRpcYSghGr8", "Post‑Quantum Security: How Lattice Cryptography Keeps Data Safe", "14:23"],
    ["e8ela6puxig", "IAM for AI: 4 Steps to Secure and Futureproof Agentic Systems", "14:39"],
    ["97DmVYRxiN0", "You Are on the Dark Web: How Phishing Leads to Data Breaches", "16:18"],
    ["lUQ2NKkCW_Q", "Agentic Trust: Securing AI Interactions with Tokens & Delegation", "12:50"],
    ["soFWS8NBcSU", "Top 10 Security Risks in AI Agents Explained", "8:59"],
    ["NH0plIdqDMk", "What is Agentic Security Runtime? Securing AI Agents", "4:59"],
    ["2fCTrjmDqyg", "Personal VPNs: Encryption Myths and Data Security Explained", "16:04"],
    ["gUNXZMcd2jU", "OWASP's Top 10 Ways to Attack LLMs: AI Vulnerabilities Exposed", "25:12"],
    ["RKeW4Xd9V9E", "2026 Threat Intelligence Index: Ransomware, AI, & Emerging TTP Risks", "6:21"],
    ["SAYmsKxNDF4", "Understanding AI Agent Security: Safeguard LLM Systems Effectively", "8:46"],
    ["UMYtqHptYvA", "Guide to Architect Secure AI Agents: Best Practices for Safety", "13:45"],
    ["xHJ0_Vm7lK8", "AI Privilege Escalation: Agentic Identity & Prompt Injection Risks", "14:35"],
    ["E_yPUsCpoC8", "Securing & Governing Autonomous AI Agents: Risks & Safeguards", "11:43"],
    ["Xc8ZuxM5YIk", "Ethical Hacking War Stories: Zero Trust, IAM & Advanced C2 Tactics", "15:17"],
    ["zMahtD8TIwc", "Do VPNs Really Protect Privacy? Data & Cybersecurity Insights", "14:17"],
    ["2jU-mLMV8Vw", "Cybersecurity Trends in 2026: Shadow AI, Quantum & Deepfakes", "20:29"],
    ["xHCCIc9n0xE", "Red Team vs Blue Team: Ethical Hacking, CTF & Cybersecurity Battles", "9:04"],
  ],
  "PLOspHqNVtKADkWLFt9OcziQF7EatuANSY": [
    ["jq_LZ1RFPfU", "Cybersecurity Architecture: Five Principles to Follow (and One to Avoid)", "17:34"],
    ["EqNe55IzjAw", "Cybersecurity Architecture: Fundamentals of Confidentiality, Integrity, and Availability", "12:34"],
    ["E9pHJRRfAhw", "Cybersecurity Architecture: Roles and Tools", "14:07"],
    ["5uNifnVlBy4", "Cybersecurity Architecture: Who Are You? Identity and Access Management", "31:15"],
    ["Njqid_JpqTs", "Cybersecurity Architecture: Endpoints Are the IT Front Door - Guard Them", "14:22"],
    ["sesacY7Xz3c", "Cybersecurity Architecture: Networks", "27:31"],
    ["nthEXs12nFE", "Cybersecurity Architecture: Application Security", "16:36"],
    ["UpkqXK0B2E0", "Cybersecurity Architecture:  Data Security", "14:48"],
    ["VEu326IZpsc", "Cybersecurity Architecture: Detection", "17:10"],
    ["Jk79QJCxPkM", "Cybersecurity Architecture: Response", "16:57"],
  ],
  "PLOspHqNVtKAB9uAIH6rAYNtiI3frm5Di0": [
    ["WYkbKzDfgqo", "What Is Ethical Hacking? Roles, Skills, and Cybersecurity", "7:23"],
    ["bSVGrA1_gYw", "Ethical Hacking in Action: Red Teaming, Pen Testing, & Cybersecurity", "17:34"],
    ["xHCCIc9n0xE", "Red Team vs Blue Team: Ethical Hacking, CTF & Cybersecurity Battles", "9:04"],
    ["2jU-mLMV8Vw", "Cybersecurity Trends in 2026: Shadow AI, Quantum & Deepfakes", "20:29"],
    ["Xc8ZuxM5YIk", "Ethical Hacking War Stories: Zero Trust, IAM & Advanced C2 Tactics", "15:17"],
  ],
  "PLOspHqNVtKAC5kOcteVAhUOuXWgqFpzkd": [
    ["NqKid53v5x8", "What is ASM (Attack Surface Management)?", "5:15"],
    ["TK8_qFp79nM", "Understanding Hackers", "10:41"],
    ["8zSoyAmHHc4", "Threats Vulnerabilities and Exploits", "5:45"],
    ["PsT2joRNvpI", "IBM Security X-Force Threat Intelligence Index Trends 2023", "4:44"],
  ],
  "PLOspHqNVtKABreqPsgh9nSNA03BicMYMC": [
    ["9RfsRn7m7OE", "What Is SIEM?", "4:29"],
    ["k7ju95jDxFA", "What is SOAR (Security, Orchestration, Automation & Response)", "7:16"],
    ["55GaIolVVqI", "What is Endpoint Detection and Response (EDR)?", "5:34"],
    ["8ZlHOZlNIKk", "EDR vs. EPP vs. NGAV", "3:53"],
  ],
  "PLZJ7euO9T11A": [
    ["b2PESRl7De4", "2026 Cost of a Data Breach Report: AI Is Changing Cybersecurity", "17:31"],
    ["7ypI1oojoII", "2025 Cost of a Data Breach: AI Risks, Shadow AI, & Solutions", "15:27"],
    ["c1K6bw5ATzk", "Cost of a Data Breach 2024 Trends", "14:29"],
  ],
  "PLOspHqNVtKADPNAxbcP2u6CPzD1g_bBhe": [
    ["lt4OsgmUTGI", "What is Quantum Computing?", "7:01"],
    ["Jx7IuJMYtJM", "How to program a quantum computer using Qiskit", "6:00"],
    ["yh789q5qur0", "Quantum Computing - Qiskit Runtime", "4:23"],
    ["NqHKr9CGWJ0", "Quantum Machine Learning Explained", "5:58"],
    ["8VnZo8wVMm8", "Quantum Computing and Chemistry", "7:55"],
    ["b7kDU22szXo", "What is Quantum Serverless?", "3:28"],
    ["kyLi8Gswpxo", "What are Quantum Primitives?", "3:17"],
    ["JCrvxWZEtSY", "Quantum Error Mitigation and the Path to Useful Quantum Computing", "10:50"],
    ["1lTA2n142Mk", "What is Quantum Safe?", "8:45"],
    ["c5t0m_nd4hk", "3 Steps to Become Quantum Safe with Crypto-agility", "6:08"],
  ],
};
