// Explainer videos for lessons and topic notes. Each id/title/channel was confirmed via YouTube oEmbed.
const V = (id, title, ch) => ({ id, title, ch });
const EXPLAINERS = {
  python: {
    basics: [V("rfscVS0vtbw", "Learn Python - Full Course for Beginners", "freeCodeCamp.org"), V("kqtD5dpn9C8", "Python for Beginners - Learn Coding with Python in 1 Hour", "Programming with Mosh")],
    strings: [V("k9TUPpGqYTo", "Python Tutorial for Beginners 2: Strings", "Corey Schafer")],
    lists: [V("W8KRzm-HUcc", "Python Tutorial for Beginners 4: Lists, Tuples, and Sets", "Corey Schafer")],
    dicts: [V("daefaLgNkw0", "Python Tutorial for Beginners 5: Dictionaries", "Corey Schafer")],
    functions: [V("9Os0o3wzS_I", "Python Tutorial for Beginners 8: Functions", "Corey Schafer"), V("QVdf0LgmICw", "Variable Scope: LEGB rule, global/nonlocal", "Corey Schafer")],
    comprehensions: [V("3dt4OGnU5sM", "Comprehensions - How they work and why to use them", "Corey Schafer"), V("bD05uGo_sVI", "Generators - How to use them and the benefits", "Corey Schafer")],
    classes: [V("ZDa-Z5JzLYM", "Python OOP Tutorial 1: Classes and Instances", "Corey Schafer")],
    errors: [V("NIWwJbo-9_8", "Using Try/Except Blocks for Error Handling", "Corey Schafer")],
    stdlib: [],
    recursion: [V("IJDJ0kBx2LM", "Recursion in Programming - Full Course", "freeCodeCamp.org")],
    testing: [V("6tNS--WetLI", "Unit Testing Your Code with the unittest Module", "Corey Schafer")],
  },
  bigo: [V("BgLTDT03QtU", "Big-O Notation - For Coding Interviews", "NeetCode"), V("__vX2sjlpXU", "Big-O notation in 5 minutes", "Michael Sambol"),
    V("itn09C2ZB9Y", "Learn Big O Notation In 12 Minutes", "Web Dev Simplified")],
  cats: {
    arrays: [V("shs0KM3wKv8", "Data Structures: Hash Tables", "HackerRank"), V("RBSGKlAvoiM", "Data Structures Easy to Advanced Course (full)", "freeCodeCamp.org")],
    twoptr: [V("PMlYYNrciJ8", "Coding Interview Pattern: Two Pointers", "Design Gurus")],
    window: [V("Mh3VKOMMqwU", "Sliding Window Algorithm - Course for Tech Interview Prep", "Alvin The Programmer")],
    stack: [V("dtiBmmIPR0E", "Monotonic Stack Explained", "Kacy Codes")],
    linked: [V("Hj_rA0dhr2I", "Linked Lists for Technical Interviews - Full Course", "freeCodeCamp.org")],
    trees: [V("cS-198wtfj0", "DFS vs BFS, When to Use Which?", "AlgoMonster")],
    heap: [V("wptevk0bshY", "Priority Queue Introduction", "WilliamFiset")],
    backtrack: [V("Zq4upTEaQyM", "The Backtracking Blueprint: The 3 Keys To Backtracking", "Back To Back SWE"), V("Ak-fxEwAR14", "Backtracking was HARD until I learned it this way", "AlgoMonster")],
    graphs: [V("tWVWeAqZ0WU", "Graph Algorithms for Technical Interviews - Full Course", "freeCodeCamp.org"), V("ibjEGG7ylHk", "Union Find Introduction", "WilliamFiset")],
    greedy: [V("-WTslqPbj7I", "Greedy Algorithms In-depth Explanation", "AlgoMonster")],
    dp1: [V("oBt53YbR9Kk", "Dynamic Programming - Learn to Solve Algorithmic Problems", "freeCodeCamp.org")],
    dp2: [V("oBt53YbR9Kk", "Dynamic Programming - Learn to Solve Algorithmic Problems", "freeCodeCamp.org")],
    math: [],
  },
  general: [V("8hly31xKli0", "Algorithms and Data Structures Tutorial - Full Course for Beginners", "freeCodeCamp.org")],
};

// Data-structure videos: "any" = concept explainers (language-agnostic), then per language.
// Each id/title/channel was confirmed via YouTube oEmbed. Bro Code's DSA series is taught in Java.
const DS_VIDEOS = {
  overview: {
    any: [V("RBSGKlAvoiM", "Data Structures Easy to Advanced Course (full)", "freeCodeCamp.org / WilliamFiset")],
    py: [V("pkYVOmU3MgA", "Data Structures and Algorithms in Python - Full Course", "freeCodeCamp.org")],
    java: [V("CBYHwZcbD-s", "Data Structures and Algorithms Full Course", "Bro Code")],
    cs: [],
  },
  array: {
    any: [],
    py: [V("gDqQf4Ekr2A", "Arrays - DSA Tutorials in Python #3", "codebasics"), V("W8KRzm-HUcc", "Lists, Tuples, and Sets", "Corey Schafer")],
    java: [V("jzJlq35dQII", "Dynamic Arrays", "Bro Code"), V("pTAda7qU4LY", "ArrayList in Java Tutorial", "Alex Lee")],
    cs: [V("vQzREQUhGSA", "C# Lists", "Bro Code"), V("VFO5vK7QjBc", "C# Arrays, Lists, and Dictionaries", "Dev Leader")],
  },
  string: {
    any: [],
    py: [V("k9TUPpGqYTo", "Strings - Working with Textual Data", "Corey Schafer")],
    java: [], cs: [],
  },
  linkedlist: {
    any: [V("njTh_OwMljA", "Data Structures: Linked Lists", "HackerRank"), V("-Yn5DU0_-lw", "Linked Lists Introduction", "WilliamFiset")],
    py: [V("qp8u-frRAnU", "Linked List - DSA Tutorials in Python #4", "codebasics")],
    java: [V("N6dOwBde7-M", "Learn Linked Lists in 13 minutes", "Bro Code")],
    cs: [V("3svB0kM6f10", "Developing a Linked List in C#", "Jeff Chastine")],
  },
  stack: {
    any: [V("L3ud3rXpIxA", "Stack Introduction", "WilliamFiset"), V("wjI1WNcIntg", "Data Structures: Stacks and Queues", "HackerRank")],
    py: [V("zwb3GmNAtFk", "Stack - DSA Tutorial in Python #7", "codebasics")],
    java: [V("KInG04mAjO0", "Learn Stack data structures in 10 minutes", "Bro Code")],
    cs: [V("tW75yz3X_M4", "Stacks and Queues in C#", "Jeff Chastine")],
  },
  queue: {
    any: [V("KxzhEQ-zpDc", "Queue Introduction", "WilliamFiset"), V("wjI1WNcIntg", "Data Structures: Stacks and Queues", "HackerRank")],
    py: [V("rUUrmGKYwHw", "Queue - DSA Tutorials in Python #8", "codebasics")],
    java: [V("nqXaPZi99JI", "Learn Queue data structures in 10 minutes", "Bro Code")],
    cs: [V("tW75yz3X_M4", "Stacks and Queues in C#", "Jeff Chastine"), V("CLByGM0iATY", "Mastering Queue, Stack and Dictionary in C#", "Bald. Bearded. Builder.")],
  },
  hashmap: {
    any: [V("shs0KM3wKv8", "Data Structures: Hash Tables", "HackerRank"), V("2E54GqF0H4s", "Hash table hash function", "WilliamFiset")],
    py: [V("ea8BRGxGmlA", "Hash Table - DSA Tutorials in Python #5", "codebasics"), V("daefaLgNkw0", "Dictionaries - Working with Key-Value Pairs", "Corey Schafer")],
    java: [V("H62Jfv1DJlU", "Map and HashMap in Java - Full Tutorial", "Coding with John"), V("FsfRsGFHuv4", "Learn Hash Tables in 13 minutes", "Bro Code")],
    cs: [V("R94JHIXdTk0", "The Dictionary Data Structure in C# in 10 Minutes", "IAmTimCorey"), V("CLByGM0iATY", "Mastering Queue, Stack and Dictionary in C#", "Bald. Bearded. Builder.")],
  },
  hashset: {
    any: [V("shs0KM3wKv8", "Data Structures: Hash Tables", "HackerRank")],
    py: [V("W8KRzm-HUcc", "Lists, Tuples, and Sets", "Corey Schafer")],
    java: [V("WPcKwA5WF7s", "Java HashSet Tutorial", "Coders Campus")],
    cs: [V("4Mi4OuSMo4A", "C# Collections: List, HashSet, Dictionary, and More", "Coderversity")],
  },
  tree: {
    any: [V("oSWTXtMglKE", "Data Structures: Trees", "HackerRank"), V("cS-198wtfj0", "DFS vs BFS, When to Use Which?", "AlgoMonster")],
    py: [V("4r_XR9fUPhQ", "Tree (General Tree) - DSA Tutorials in Python #9", "codebasics")],
    java: [], cs: [],
  },
  bst: {
    any: [V("JfSdGQdAzq8", "Binary Search Tree Introduction", "WilliamFiset"), V("oSWTXtMglKE", "Data Structures: Trees", "HackerRank")],
    py: [V("lFq5mYUWEBk", "Binary Search Tree - DSA Tutorials in Python #10", "codebasics")],
    java: [],
    cs: [V("dYWz6wqvEEs", "Binary Search Trees in C#", "Jeff Chastine")],
  },
  heap: {
    any: [V("t0Cq6tVNRBA", "Data Structures: Heaps", "HackerRank"), V("wptevk0bshY", "Priority Queue Introduction", "WilliamFiset")],
    py: [],
    java: [V("7z_HXFZqXqc", "Learn Priority Queue data structures in 5 minutes", "Bro Code")],
    cs: [V("d262kUQKT0E", "Master the PriorityQueue - A New Collection in .NET", "Zoran on C#"), V("49ELFZLqOUo", "Top K Algorithm in C# Using PriorityQueue", "Andrea Angella")],
  },
  trie: {
    any: [V("zIjfhVPRZCg", "Data Structures: Tries", "HackerRank")],
    py: [], java: [],
    cs: [V("4nmVXKu6e_Q", "Lets Make a Simple Prefix Tree in C#", "World of Zero")],
  },
  graph: {
    any: [V("zaBhtODEL0w", "Algorithms: Graph Search, DFS and BFS", "HackerRank"), V("tWVWeAqZ0WU", "Graph Algorithms for Technical Interviews", "freeCodeCamp.org")],
    py: [V("j0IYCyBdzfA", "Graph Introduction - DSA Tutorials in Python #12", "codebasics")],
    java: [V("-VgHk7UMPP4", "Learn Graphs in 5 minutes", "Bro Code")],
    cs: [V("ZSrYF20BcAY", "Graph Data Structure in C#: Adjacency List & Matrix", "TechWebDots")],
  },
  unionfind: {
    any: [V("ibjEGG7ylHk", "Union Find Introduction", "WilliamFiset")],
    py: [], java: [], cs: [],
  },
};

// YouTube video IDs for problem solutions (NeetCode channel). Each was checked via YouTube oEmbed: uploader is NeetCode
// and the title names the problem. Problems missing here fall back to a YouTube search link.
const VIDEOS = {
  "two-sum": "KLlXCFG5TnA", "valid-anagram": "9UtInBqnCgA", "contains-duplicate": "3OamzN90kPg",
  "group-anagrams": "vzdNOK2oB2E", "top-k-frequent-elements": "YPTqKIgVk-k", "product-of-array-except-self": "bNvIQI2wAjk",
  "valid-palindrome": "jJXJ16kPFWg", "two-sum-ii-input-array-is-sorted": "cQ1Oz4ckceM", "3sum": "jzZsG8n2R9A",
  "best-time-to-buy-and-sell-stock": "1pkOgXD63yU", "longest-substring-without-repeating-characters": "wiGpQwVHdE0",
  "valid-parentheses": "WTzjTskDFMg", "min-stack": "qkLl7nAwDPo", "daily-temperatures": "cTBiBSnjO3c",
  "binary-search": "s4DPM8ct1pI", "search-a-2d-matrix": "Ber2pi2C0j0", "reverse-linked-list": "G0_I-ZF0S38",
  "merge-two-sorted-lists": "XIdigk956u0", "linked-list-cycle": "gBTe7lFR3vc", "invert-binary-tree": "OnSn2XEQ4MY",
  "maximum-depth-of-binary-tree": "hTM3phVI6YQ", "same-tree": "vRbbcKXCxOw",
  "lowest-common-ancestor-of-a-binary-search-tree": "gs2LMfuOR9k", "binary-tree-level-order-traversal": "6ZnyEApgFYg",
  "validate-binary-search-tree": "s6ATEkipzow", "last-stone-weight": "B-QCq79-Vfw",
  "kth-largest-element-in-an-array": "XEmy13g1Qxc", "generate-parentheses": "s9fokUqJ76A", "subsets": "REOH22Xwdkk",
  "combination-sum": "GBKI9VSKdGg", "permutations": "s7AvT7cGdSo", "number-of-islands": "pV2kpPD66nE",
  "course-schedule": "EgI5nU9etnU", "maximum-subarray": "5WZl3MMT0Eg", "merge-intervals": "44H3cEC2fFM",
  "plus-one": "jIaA8boiG1s", "climbing-stairs": "Y0lT9Fck7qI", "min-cost-climbing-stairs": "ktmzAZWkEZ0",
  "house-robber": "73r3KWiEvyk", "coin-change": "H9bfqozjoqs", "unique-paths": "IlEsdxuD4lY",
  "remove-duplicates-from-sorted-array": "DEJAZBq0FDA", "move-zeroes": "aayNRwUN3Do",
  "container-with-most-water": "UuiTKBwPgAo", "trapping-rain-water": "ZI2z5pq0TqA",
  "longest-repeating-character-replacement": "gqXU1UyA8pk", "permutation-in-string": "UbyhOgBN834",
  "minimum-window-substring": "jSto0O4AJbM", "largest-rectangle-in-histogram": "zx5Sw9130L0",
  "koko-eating-bananas": "U2SozAs9RzA", "find-minimum-in-rotated-sorted-array": "nIVW4P8b1VA",
  "search-in-rotated-sorted-array": "U8XENwh8Oy8", "lru-cache": "7ABFKPK2hD4", "merge-k-sorted-lists": "q5a5OiGbT6Q",
  "reorder-list": "S5bfdUTrKLM", "remove-nth-node-from-end-of-list": "XVuQxVej6y8", "add-two-numbers": "wgFPrzTjm7s",
  "clone-graph": "mQeF6bN8hMk", "rotting-oranges": "y704fEOx0s0", "word-search": "pfiQ_PS1g8E",
  "longest-increasing-subsequence": "cjWnW0hdF1Y", "word-break": "Sx9NNgInc3A", "decode-ways": "6aEyTjOwlJU",
  "longest-common-subsequence": "Ua0GhsJSlWM", "edit-distance": "XYi2-LPrwm4", "course-schedule-ii": "Akt3glAwyfY",
  "number-of-1-bits": "5Km3utixwZs", "kth-largest-element-in-a-stream": "hOjcdrqMoQ8",
  "diameter-of-binary-tree": "bkxqA8Rfv04", "balanced-binary-tree": "QfJsau0ItOY", "subtree-of-another-tree": "E36O5SWp-LE",
  "kth-smallest-element-in-a-bst": "5LUXSvjmGCw", "binary-tree-right-side-view": "d4zLyf32e3I",
  "count-good-nodes-in-binary-tree": "7cp5imvDzl4",
  "construct-binary-tree-from-preorder-and-inorder-traversal": "ihj4IQGZ2zc", "binary-tree-maximum-path-sum": "Hr5cWUld4vU",
  "serialize-and-deserialize-binary-tree": "u4JAi2JJhI8", "task-scheduler": "s8p8ukTyA2I",
  "find-median-from-data-stream": "itmhHWaHupI", "k-closest-points-to-origin": "rI2EBUEMfTk",
  "longest-palindromic-substring": "XYQecbcd6_c", "rotate-image": "fMSJSS7eO1w", "spiral-matrix": "BJnMZNwUk1M",
  "set-matrix-zeroes": "T41rL0L3Pnw", "palindrome-partitioning": "3jvWodd7ht0",
  "letter-combinations-of-a-phone-number": "0snEunUacZY", "n-queens": "Ph95IHmRp5M", "insert-interval": "A8NUOmlwOlM",
  "non-overlapping-intervals": "nONCGxWoUfM", "pacific-atlantic-water-flow": "s-VkcjHqkGI", "surrounded-regions": "9z2BunfoZ5Y",
  "network-delay-time": "EaphyqKU4PQ", "cheapest-flights-within-k-stops": "5eIK3zUdYmE", "word-ladder": "h9iTnkgv05E",
  "partition-equal-subset-sum": "IsvocB5BJhw", "coin-change-ii": "Mjy4hd2xgrs", "target-sum": "g0npyaQtAQM",
  "best-time-to-buy-and-sell-stock-with-cooldown": "I7j0F7AHpb8", "powx-n": "g9YQyYi4IQQ", "reverse-integer": "HAgLH58IgJQ",
  "jump-game-ii": "dJ7sWiOoK7g", "gas-station": "lJwbPZGo05A", "partition-labels": "B7m8UmZE-vw",
  "word-search-ii": "asbcE9mZz_U", "design-add-and-search-words-data-structure": "BTf05gs_8iU",
  "time-based-key-value-store": "fu2cD_6E8Hw", "median-of-two-sorted-arrays": "q6IEA26hvXc",
  "sliding-window-maximum": "DfljaUwZsOk", "car-fleet": "Pr6T-3yB9RM", "copy-list-with-random-pointer": "5Y2EiZST97Y",
  "evaluate-reverse-polish-notation": "iu0082c4HDE", "subarray-sum-equals-k": "fFVZt-6sgyo",
  "longest-consecutive-sequence": "P6RZZMu_maU", "valid-sudoku": "TjFXEUCMqI8", "rotate-array": "BHr381Guz3Y",
  "counting-bits": "RyBM56RIWrM",
};
